### ISSUE TITLE
Sending data through logstash leads to two timestamp fields

### ISSUE THREAD

**Issue by ruflin** [elastic/filebeat#120]
Sending data from filebeat to logstash to elasticsearch leads to two timestamp fields

* timestamp (coming from filebeat)
* @timestamp (coming from ?)

The timestamps are not identical. I assume logstash adds the @timestamp.

Questions:
* Should we keep both timestamps? 
* Do we need both timestamps?

It makes the setup of the Kibana dashboard a little bit less obvious as two fields pop up:

![screen shot 2015-10-21 at 10 01 04](https://cloud.githubusercontent.com/assets/244900/10631197/913ee35c-77dc-11e5-94b5-812abfead53b.png)

**Comment by urso** [comment]
Yes, @timestamp is added by logstash: https://github.com/elastic/logstash/blob/master/lib/logstash/event.rb

**Comment by urso** [comment]
If we send "@timestamp" ourselves, logstash will try to validate the timestamp value. If validation fails, logstash overwrites value with current system time. If "@timestamp" is missing, logstash will add it.

**Comment by ph** [comment]
@urso the `timestamp` from filebeat is when the event was created right? This is the same default behavior for logstash. When we create an event we will assign a default `@timestamp` value, we expect people to use grok or other manipulation to extract the real 'timestamp` of the event (like from an apache log).

So I think for our case we should initialize the logstash event with the timestamp send by beats, unless people use grok to extract the real date from the actual data.

What do you think?

**Comment by urso** [comment]
I think there's a general confusion about @timestamp vs timestamp in general. We should just have one.

**Comment by ph** [comment]
@urso Agree, So how which side we fixed that ;)

**Comment by urso** [comment]
both I would say ;)

**Comment by sijocherian** [comment]
same issue. Is there a way to customize the fields going with filebeat: "source", "timestamp" etc. No configuration in evident

**Comment by mrkschan** [comment]
i guess this is fixed in https://github.com/elastic/filebeat/pull/168/?

**Comment by urso** [comment]
right
