### ISSUE TITLE
Add Window Event Log support to beats

### ISSUE THREAD

**Issue by tbragin** [elastic/filebeat#130]
Windows Event Log is a custom binary file format, reading which is not currently supported by Filebeat. We should either add this support or create a new beat that allows consuming and processing these logs. 

Migrated from: https://github.com/elastic/logstash-forwarder/issues/485

**Comment by elvarb** [comment]
And automatic parsing of fields, similar to nxlog.

**Comment by lmello** [comment]
It would be very nice if it could access remote windows eventlog. Just in case you can't install the beats agent on one server, but you have access to the event log remotely.

**Comment by andrewkroh** [comment]
@lmello Thanks for the feedback. We will keep it in mind. The Windows APIs support retrieving events from remote machines so it should be feasible for the Beat to pull remote events (the Beat still needs to run on Windows). The downside with this approach is that if you receive events from XP or Windows 2003 you must have the same event message files (DLLs and EXEs) available locally to interpret the contents of the event.

Another avenue for collecting remote events is to use the Windows Event Forwarder service to forward the events to a server where the Beat is running. It still suffers from the issues for XP and Win 2003.

**Comment by Jakauppila** [comment]
+1 to @lmello suggestion. While we will be exploring Beats to replace NXLog as it matures and could potentially ship event logs, it simplifies the config if we could just configure a set of event log collectors to remotely grab them.

**Comment by stephanbuys** [comment]
@tbragin, if this is targeted for v1.1.0 is there any resource to track progress? I'm considering jumping in and contributing some of this code but I don't want to double up on work the Elastic is already undertaking.

**Comment by ruflin** [comment]
@stephanbuys I think @andrewkroh already started with a prototype. He is the best person to talk to.

**Comment by stephanbuys** [comment]
@ruflin thanks - @andrewkroh, would be great to have a chat re this, or perhaps get some idea. I'm assuming its being internally developed and then pushed out?

**Comment by lmello** [comment]
Just to let everyone know the work around would bem to use Windows event
log subscription to a management server the use the current  agent on the
management server. But this would not scale.

**Comment by stephanbuys** [comment]
That's interesting was the scaling problem on the centralised approach? Or with the subscription mechanism?

**Comment by andrewkroh** [comment]
@stephanbuys I would be happy to chat about this and welcome contributions. I started writing some code a few weeks ago when I had some downtime during travel. I setup an eventbeat project today with code, but we haven't decided whether this is going to be standalone or part of Filebeat.

See https://github.com/elastic/eventbeat/issues/1

**Comment by tsg** [comment]
Windows events logs are now available via [Winlogbeat](https://www.elastic.co/downloads/beats/winlogbeat).

**Comment by dculp** [comment]
@lmello were you ever able to accomplish access remotely?

**Comment by andrewkroh** [comment]
@dculp If you have questions regarding Winlogbeat, I suggest posting at https://discuss.elastic.co/c/beats/winlogbeat (your questions will reach a wider audience).
