### ISSUE TITLE
Make type field dynamic based on input

### ISSUE THREAD

**Issue by ruflin** [elastic/filebeat#133]
Currently the type of an event is hardcoded to "log". This must be dynamic based on the harvester that was started in the prospector config.

This line must be changed: https://github.com/elastic/filebeat/blob/master/input/file.go#L58

**Comment by urso** [comment]
@ruflin can you check whether #153 correctly addresses this ticket?

**Comment by ruflin** [comment]
@urso Right direction :-)

**Comment by ruflin** [comment]
Done by #153
