### ISSUE TITLE
Support a "batch" mode

### ISSUE THREAD

**Issue by erik-stephens** [elastic/filebeat#134]
A cmd-line flag or configuration option to have filebeat exit once all prospectors have reached end-of-file would help support integration testing efforts.  The use case is to start filebeat with a known set of files, ship them to a test instance of logstash, and then compare the results.  There are some workarounds I can think of:

- kill filebeat after a set time
- grep filebeat output for "no events to publish"

While not important for my use case, might want to think about exit codes, like what to return if unable to ship all events.

**Comment by ruflin** [comment]
Thanks for opening the issue. In your system tests we actually check the log output for some messages like this: https://github.com/elastic/filebeat/blob/master/tests/system/test_crawler.py#L330 But this is not very nice and reliable.

For reference: https://discuss.elastic.co/t/testing-filebeat-logstash/32811

**Comment by ruflin** [comment]
I think this is very similar to https://github.com/elastic/beats/issues/880. Closing this one in favor of https://github.com/elastic/beats/issues/880
