### ISSUE TITLE
test scenario with large amount of files eligible for processing

### ISSUE THREAD

**Issue by nellicus** [elastic/filebeat#141]
what happens when filebeat is expected to process thousands of files?

to be tested

**Comment by ruflin** [comment]
As the OS runs out of file descriptors in this case which either blocks filebeat or on Windows errors are returned, we introduced `harvester_limit` in the most recent version which should solve this issue: https://www.elastic.co/guide/en/beats/filebeat/master/configuration-filebeat-options.html#_harvester_limit

**Comment by nellicus** [comment]
great work @ruflin !
