### ISSUE TITLE
when logstash is stop,filebeat eat  100% cpu

### ISSUE THREAD

**Issue by yucl80** [elastic/filebeat#144]
when logstash is stop,filebeat eat  100% cpu

**Comment by ruflin** [comment]
@yucl80 I tried to reproduce this but couldn't so far. Can you provide me the following info?

* Operation system
* Filebeat Version
* Logstash Version
* Elasticsearch Version

**Comment by yucl80** [comment]
Linux  2.6.18-164.el5 #1 SMP Tue Aug 18 15:51:48 EDT 2009 x86_64 x86_64 x86_64 GNU/Linux
filebeat-1.0.0-beta4-x86_64

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                              
26982 mwuser    15   0  235m  11m 3724 S 133.7  0.1   0:52.43 filebeat

**Comment by yucl80** [comment]
Logstash 1.5.4
Elasticsearch  1.7.3

**Comment by ruflin** [comment]
@yucl80 I assume this is RHEL 5.4?

**Comment by ruflin** [comment]
Currently we only support CentOS >= 6 as CentOS 5 is officially also not supported by Golang. For the compatibility matrix have a look here: https://www.elastic.co/support/matrix

As you got it running, I assume you installed it from source and not the rpm?

**Comment by mortont** [comment]
I would like to reopen this issue. I can confirm that filebeat-1.0.0-beta4 uses 100% cpu when unable to connect to Logstash. Filebeat was installed from the rpm at https://download.elastic.co/beats/filebeat/filebeat-1.0.0-beta4-x86_64.rpm. We are using CentOS 6.4, Logstash 2.0, and Elasticsearch 2.0. Also saw this behavior when used with Logstash 1.5.4 and Elasticsearch 1.7.3.

I originally came across this issue when trying to connect to a misconfigured Logstash, then again later when network ports weren't open.

When Logstash and Filebeat are both running correctly there is no issue. Then, if you kill Logstash there is no spike in cpu usage but if you restart Filebeat while Logstash is down, Filebeat will use 100% cpu. Even after starting Logstash again Filebeat will use 100% cpu until Filebeat has been restarted.

Let me know if there is any other information you need from me to help diagnose this.

**Comment by ruflin** [comment]
@mortont I reopened the issue and will try to reproduce it.

**Comment by ruflin** [comment]
@mortont Are you using the logstash config found in our documentation? https://www.elastic.co/guide/en/beats/libbeat/current/configuration.html#logstash-output

**Comment by mortont** [comment]
I am not using the config from the documentation verbatim, but here is the config I am using for filebeat: https://gist.github.com/mortont/fe405b28bef874ca4496

This is the config for logstash if you think it might be relevant:
```
input {
  tcp {
    port => 10514
    type => syslog
  }
  udp {
    port => 10514
    type => syslog
  }
  beats {
    port => 5043
    type => syslog
  }
}

filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    syslog_pri { }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}

output {
  elasticsearch { hosts => localhost }
  stdout { codec => rubydebug }
}
```

**Comment by andrewkroh** [comment]
I think I am also seeing this issue. I just start filebeat on my mac with the default config and without ES running. Steps to reproduce:

```
git clone https://github.com/elastic/filebeat.git
cd filebeat
git checkout 1af66bfaebaeaf80438f5a61b1ea9c3b6e89ecc2   # master at this time
make
./filebeat -c etc/filebeat.yml -e -d '*'
```

![Activity Monitor](https://cloud.githubusercontent.com/assets/4565752/10871983/65f780cc-80c5-11e5-8ee1-69ae7ba942fc.png)

**Comment by andrewkroh** [comment]
The high CPU usage seems to be caused by the [tight retry loop](https://github.com/elastic/libbeat/blob/master/publisher/sync.go#L53) that results when using the sync publisher with the `forceForward` option. There needs to be some rate limiting with this loop.

Attached is a [stacktrace](https://github.com/elastic/filebeat/files/25068/filebeat-stack.txt) I took while filebeat was running. See goroutine 21. Also there are about 1000 goroutines being created and destroyed every few seconds. The attached stacktrace has 235 of them at the end.

[filebeat-stack.txt](https://github.com/elastic/filebeat/files/25068/filebeat-stack.txt)

**Comment by ruflin** [comment]
@andrewkroh Was also able to reproduce it with your steps above. @urso FYI

**Comment by urso** [comment]
I managed to reproduce this if only one host is configured. Can you confirm only one host being configured?

**Comment by andrewkroh** [comment]
@mortont @yucl80 Thanks for reporting this. The fix should be available in the [nightly build](
https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/) after a few hours.
