### ISSUE TITLE
filebeat on windows locks log file

### ISSUE THREAD

**Issue by dmitriyett** [elastic/filebeat#145]
I've tried to set up filebeat and logstash instances for logging and I've encountered an issue. Filebeat locks log files for write, so my program can't append anything there. My filebeat.yml config file:
```
filebeat:
  prospectors:
    -
      paths:
        - "D:\\Repositories\\logstashtests\\logs.txt"
      type: log
output:
  logstash:
    enabled: true

    hosts: ["127.0.0.1:5044"]
```

logstash.conf:
```
input {
	beats {
		port => 5044
	}
}

output {
	stdout {}
}
```

There are also three other issues but I don't know wheather they are related to my original issue or not.
1) When I start filebeat it outputs following text to console:

```
service_windows.go:45: ERR Error: The service process could not connect to the service controller.
```

2) when Logstash receives a log it prints to console (because I'm using stdout output)

```
2015-10-27T11:29:40.979Z %{host} this is a log
2015-10-27T11:29:40.981Z %{host} asdasdasd
2015-10-27T11:29:40.983Z %{host} new
```

For some reason it can't correctly fill %{host} placeholder.

3) After I close filebeat by pressinc CTRL + C I'm receiving following error message in logstash (yes, in logstash, not in filebeat): 

```
[31mBeats input: unhandled exception {:exception=>#<SystemCallError: Unknown error - ????????? ???? ????????????? ???????? ???????????? ???????????>, :backtrace=>["org/jruby/RubyIO.java:3020:in `sysread'", "D:/Repositories/logstashtests/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:330:in `read_socket'", "D:/Repositories/logstashtests/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:315:in `run'", "D:/Repositories/logstashtests/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/logstash/inputs/beats.rb:150:in `invoke'", "org/jruby/RubyProc.java:271:in `call'", "D:/Repositories/logstashtests/logstash-1.5.4/logstash-1.5.4/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.1-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_102551874.gen:13:in `run'"], :level=>:error}[0m
```

If this problems are not related to main one, I can create separate issues for them

**Comment by ruflin** [comment]
I assume your first issue is somehow also related to: https://github.com/elastic/filebeat/issues/93 I'm currently looking into this.

For the other issues: They should not be related to here some notes on it:
* Number 1 seems to be related to libbeat: https://github.com/elastic/libbeat
* For number 2 and 3 it is probably best to file an issue in the logstash repository: https://github.com/elastic/logstash

**Comment by ruflin** [comment]
@dmitriyett Did your apps print out any specific error message on why they can't write to the log file? Would be nice if we could get here some more information. The problem we are aware of is the issue of (re)moving files because they are open.

**Comment by tsg** [comment]
Just to confirm, 1 is not related, and can be ignored when running in foreground. We should find a way to not.print that error, so an issue posted would be appreciated.

**Comment by dmitriyett** [comment]
>Number 1 seems to be related to libbeat: https://github.com/elastic/libbeat

>Just to confirm, 1 is not related, and can be ignored when running in foreground. We should find a way to not.print that error, so an issue posted would be appreciated.

I'll file the issue there, thank you.

>For number 2 and 3 it is probably best to file an issue in the logstash repository: https://github.com/elastic/logstash

I'll do

>Did your apps print out any specific error message on why they can't write to the log file? Would be nice if we could get here some more information. The problem we are aware of is the issue of (re)moving files because they are open.

Unfortunately I can't provide error message right now, I'll add it later.

**Comment by urso** [comment]
2 is expected. Plain events from filebeat do not contain a 'host' field. That's why %{host} is displayed in stdout. See [export fields doc](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields.html). You might want to use 'shipper' instead of host e.g. using a filter.

3 Looks like some missing exception handler in [logstash-input-beats](https://github.com/logstash-plugins/logstash-input-beats)

**Comment by dmitriyett** [comment]
I'm writing a .NET application and I'm using NLog library to write logs to log files. After I start filebeat I'm receiving following exception:

```
System.IO.FileLoadException: The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x080070020)
```

And here is the message, that I can see from internal logging information:

```
2015-10-28 02:01:07.5259 Trace Opening logs.txt with allowFileSharedWriting=False
```

But you do not need a project or NLog themselves. You can try to edit log file in notepad, and you will see same issue.

**Comment by ruflin** [comment]
@dmitriyett Can you briefly state which Windows version you are using and which file system? I thought I saw it somewhere before but couldn't find it anymore.

**Comment by dmitriyett** [comment]
@ruflin Windows 10, build 10240. File system: NTFS. 
Filebeat version 1.0.0-beta4. Logstash version 1.5.4. logstash-input-beats version 0.9.2.
Thank you

**Comment by ruflin** [comment]
@dmitriyett Will try to get my hands on a Windows 10 machine. So far we only tried and tested it on Windows Server 2012.

**Comment by ruflin** [comment]
@dmitriyett What is the system version you would plan to run it in production?

**Comment by dmitriyett** [comment]
@ruflin Windows server 2008 r2. I think I can test filebeat with it a bit later. I'll try and I'll write details after.

**Comment by ruflin** [comment]
@dmitriyett It looks like @tsg found the potential issue and also fixed it here: https://github.com/elastic/filebeat/pull/156

I'm currently building a snapshot with the current version which should be available in about 30 minutes here: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/ Could you try it again with the snapshot?

**Comment by dmitriyett** [comment]
@ruflin yes, it fixed the issue. Thanks a lot. Saved a lot of time)
Should I close the issue then?

**Comment by ruflin** [comment]
@dmitriyett Yes. I directly closed it. In case the same issue reappears, feel free to open it again.
