### ISSUE TITLE
Config file for windows ships with unicode character that breaks the yaml parser

### ISSUE THREAD

**Issue by DanielLaberge** [elastic/filebeat#151]
The following line in filebeat.yml shipped in filebeat-1.0.0-beta4-windows.zip contains an unicode character that breaks the yaml parser with this error: 
*YAML config parsing failed on filebeat.yml: yaml: control characters are not allowed. Exiting.*

This is the line in question:
  **registry_file: "C:/ProgramData/[illegal char here]ilebeat/registry"**

Took me a good 10 minutes to figure that out using an online YAML parser which provided more detail about the error than filebeat did.

**Comment by ruflin** [comment]
@DanielLaberge Thanks a lot for reporting this. We fixed this a few minutes ago with this pull request here: https://github.com/elastic/filebeat/pull/150

**Comment by ruflin** [comment]
@DanielLaberge I will close this as duplicate of https://github.com/elastic/filebeat/issues/149 Please reopen in case this is a different issue.

**Comment by DanielLaberge** [comment]
Thanks for the quick fix.
