### ISSUE TITLE
@timestamp that filebeat is sending is not understood by logstash

### ISSUE THREAD

**Issue by coffeepac** [elastic/filebeat#178]
on the nightly from last night (11/1/2015) filebeat is sending the @timestamp value as a string, this is causing the logstash-2.0.0 input beats to drop the following error message:

{:timestamp=>"2015-11-03T00:21:47.613000+0000", :message=>"Beats input: unhandled exception", :exception=>#<TypeError: The field '@timestamp' must be a (LogStash::Timestamp, not a String (2015-11-03T00:21:46.460Z)>, :backtrace=>["/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/event.rb:138:in `[]='", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/logstash/inputs/beats.rb:138:in `create_event'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/logstash/inputs/beats.rb:138:in `create_event'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-codec-plain-2.0.2/lib/logstash/codecs/plain.rb:35:in `decode'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/logstash/inputs/beats.rb:136:in `create_event'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/logstash/inputs/beats.rb:150:in `invoke'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:370:in `data'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:349:in `read_socket'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:361:in `ack_if_needed'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:345:in `read_socket'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:246:in `json_data_payload'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:163:in `feed'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:296:in `compressed_payload'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:163:in `feed'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:330:in `read_socket'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/lumberjack/beats/server.rb:315:in `run'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/logstash-input-beats-0.9.2/lib/logstash/inputs/beats.rb:150:in `invoke'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.1-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_429565255.gen:13:in `run'"], :level=>:error}

This error does not occur with filebeat-1.0.0-beta4.

**Comment by urso** [comment]
it's related to logstash-plugins/logstash-input-beats#10. We have had to update 'timestamp' tim '@timestamp' in all beats since beta4. Unfortunately you have to update the logstash-input-beats plugin to get the fix. From logstash directory this command should update the plugin:

    $ bin/plugin update logstash-input-beats

**Comment by coffeepac** [comment]
whoa, crazy.  okay, I pulled down logstash2 this afternoon.  will pull and try again.

**Comment by coffeepac** [comment]
rad, that took care of it.

Closing, thanks for the help @urso
