### ISSUE TITLE
Better document changes to fields from lsf to filebat

### ISSUE THREAD

**Issue by ruflin** [elastic/filebeat#179]
Coming from logstash-forwarder the fields config option was used for the type and all fields inside were automatically copied to the root. Under filebeat a nested document with fields inside is generated. This leads to confusion with existing lsf users and breaks some dashboards.

Type can no be configured per prospector with the document_type option. Fields are nested in document to not conflict with other fields coming from filebeat or libbeat. Like this no field conflict management has to be done. Tags would be an other name but is already used as parts of the shipper config. It should be discussed if tags should be used and merged with shipper.tags before sending.

See https://discuss.elastic.co/t/custom-fields-are-not-stored-in-the-message-root/33585

* Document what changes were made and what the intention is (conflicts).
* Discuss potential renaming.

**Comment by monicasarbu** [comment]
The fix is coming in the PR: https://github.com/elastic/filebeat/pull/188

**Comment by ruflin** [comment]
@monicasarbu Should we also add a note to the migration guide?

**Comment by tsg** [comment]
@ruflin we gather things for the migration guide in #189. There's already a point about this one.

**Comment by ruflin** [comment]
Yep, added it :-) Closing this one here.
