### ISSUE TITLE
FileBeat trying to get a write-lock on files causes Error creating file '%!s(*uint16=0x126ac000)' on Windows IIS logs

### ISSUE THREAD

**Issue by Cylindric** [elastic/filebeat#184]
I am testing out Filebeat for managing IIS logs, and get the following error when I run

    filebeat.exe -c filebeat.yml -v

The console output is:

	d:\filebeat>filebeat.exe -c filebeat.yml -v
	geolite.go:52: WARN Couldn't load GeoIP database
	publish.go:222: WARN No output is defined to store the topology. The server fields might not be filled.
	publish.go:234: INFO No shipper name configured, using hostname 'MarkDesktop'
	registrar.go:75: INFO Loading registrar data from d:\filebeat/.filebeat
	service_windows.go:45: ERR Error: The service process could not connect to the service controller.
	log.go:140: ERR Failed opening C:\inetpub\logs\LogFiles\W3SVC1\u_ex151103.log: Error creating file '%!s(*uint16=0x125fc6c0)': The process cannot access the file because it is being used by another process.
	crawler.go:77: INFO All prospectors initialised with 66 states to persist
	log.go:140: ERR Failed opening C:\inetpub\logs\LogFiles\W3SVC1\u_ex151103.log: Error creating file '%!s(*uint16=0x126ac000)': The process cannot access the file because it is being used by another process.
	log.go:140: ERR Failed opening C:\inetpub\logs\LogFiles\W3SVC1\u_ex151103.log: Error creating file '%!s(*uint16=0x126f6000)': The process cannot access the file because it is being used by another process.
	log.go:140: ERR Failed opening C:\inetpub\logs\LogFiles\W3SVC1\u_ex151103.log: Error creating file '%!s(*uint16=0x125d63c0)': The process cannot access the file because it is being used by another process.
	log.go:140: ERR Failed opening C:\inetpub\logs\LogFiles\W3SVC1\u_ex151103.log: Error creating file '%!s(*uint16=0x126ac0c0)': The process cannot access the file because it is being used by another process.

Why is FileBeat trying to get a write-lock on the log file? Can't it just get a generic read lock?
Using ProcMon I can see it's trying to open the file with:

    Desired Access: Generic Reade/Write

This is my filebeat.yml

	filebeat:
	  prospectors:
		-
		  paths:
			- "C:/inetpub/logs/LogFiles/W3SVC1/*.log"
		  fields:
			type: iis

	output:
	  elasticsearch:
		enabled: false

	  logstash:
		enabled: true
		hosts: ["logstash.communigator.co.uk:5044"]

	shipper:

**Comment by Cylindric** [comment]
Apologies, I see there's already a commit https://github.com/elastic/filebeat/commit/a3bdda7945ac7b5058a9a62d3ca65618cceea888 that addresses this

No idea how to build a Go project, so I'll have to wait for a release. :)

**Comment by ruflin** [comment]
@Cylindric Yep, should be fixed now. We also have the nightly builds here: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/

I will close this issue but feel free to reopen it in case the problem still occurs with the newest version.
