### ISSUE TITLE
Review the migration guide

### ISSUE THREAD

**Issue by tsg** [elastic/filebeat#189]
We should go again over the migration guide and update it with what we learned since the beta4 release.

Things I know about:

* [x] Explain the `fields_under_root` option
* [x] Mention changes to fields: https://github.com/elastic/filebeat/issues/179 #138
* [x] Check if the `tail_files` is correctly used in the samples. Maybe mention it explicitly if it is not.
* [x] Mention host #208
* [x] File was changed to source
* [ ] How to update logstash-input-beats plugin

**Comment by tsg** [comment]
Feel free to add more items, the threads on discuss & github are good at pointing out where people stumble.

**Comment by urso** [comment]
tell people to use more stable version of logstash-input-beats plugin (0.9.2 has well known bugs failing with recent beats)

**Comment by nxhack** [comment]
Mention change field in LSF migration guide. filter code example like that.
```javascript
  if [beat][hostname] {
    if ![host] {
      mutate {
        add_field => { "host" => "%{[beat][hostname]}" }
      }
    }
    if ![file] {
      mutate {
        add_field => { "file" => "%{source}" }
      }
    }
  }
```

**Comment by dedemorton** [comment]
@tsg Wondering if dev will take a first pass at adding these changes, or if you want me to do it. I've just submitted a pull request that contains my technical edits to the existing file, so now would be a good time for someone to make these updates. I'd like to take a pass at editing whatever gets added.

**Comment by tsg** [comment]
@dedemorton i merged that PR and now we'll try to add the missing content. I'll ping you afterwards.

**Comment by tsg** [comment]
Implemented  most of this in: https://github.com/elastic/filebeat/pull/266
