### ISSUE TITLE
filebeat windows build - not idempotent startup script

### ISSUE THREAD

**Issue by coffeepac** [elastic/filebeat#196]
Hello Team,
The startup script that ships with the filebeat windows build doesn't work on win2k8r2.  The script checks if the filebeat service is installed, if it is the script attempts to delete the running service and reinstall.  However, the service needs to be stopped before windows will let the service be removed.  Windows will happily accept your call to delete and mark the service for deletion but won't remove the service until the process stops.

I'd make the fix and include a PR but I can't tell where in this repo that script exists.

Pat

**Comment by tsg** [comment]
Hi, the script is generate from [this](https://github.com/elastic/beats-packer/blob/master/platforms/windows/uninstall-service.ps1.j2) template file. We would happily accept a PR on it or we can make it ourselves if you provide an example.

**Comment by coffeepac** [comment]
well, that would explain why I couldn't find it.  I'll open a PR over there and close this out when done.

**Comment by coffeepac** [comment]
@tsg PR opened on packer beats:  https://github.com/elastic/beats-packer/pull/21  want this bug closed or leave it until the associated PR is handled?

**Comment by tsg** [comment]
Thanks, just merged that one. Next nightly should have the new script and we also plan to release RC1 tomorrow.

**Comment by coffeepac** [comment]
oh dag, RC1 tomorrow?  awesome.  thanks man!
