### ISSUE TITLE
Registrar does not persist data on all prospected files

### ISSUE THREAD

**Issue by andrewkroh** [elastic/filebeat#200]
I think the persisted registry should contain data on all files that Filebeat's prospector encounters, not just the ones from which an event is published.

Consider this situation, I have many old, large log files that Filebeat sees but ignores. I stop Filebeat. Some service decides to write to one of those old log files. I restart Filebeat and now Filebeat decides to send all lines from that old file. What I would expect is that just the new lines would be sent.

**Comment by ruflin** [comment]
:+1:

**Comment by ruflin** [comment]
This could now be done with using tail_files first and then the state is stored as `ignore_older` is set to infinity by default. But it gets now more complex with the new `clean_*` options. I would close this one. Please reopen if you think we should do some more changes here.
