### ISSUE TITLE
Panic on close on windows

### ISSUE THREAD

**Issue by tsg** [elastic/filebeat#204]
When using ^C on windows, I get the following:

<pre>
PS C:\Users\vagrant\filebeat-1.0.0-rc1-windows> vim .\filebeat.yml
PS C:\Users\vagrant\filebeat-1.0.0-rc1-windows> .\filebeat.exe -e -c .\filebeat.yml
panic: close of closed channel

goroutine 22 [running]:
github.com/elastic/filebeat/beat.(*Filebeat).Stop(0x126e9820)
        /go/src/github.com/elastic/filebeat/beat/filebeat.go:115 +0x2f
github.com/elastic/libbeat/beat.(Beater).Stop-fm()
        /go/src/github.com/elastic/filebeat/Godeps/_workspace/src/github.com/elastic/libbeat/beat/beat.go:127 +0x2d
github.com/elastic/libbeat/service.HandleSignals.func2()
        /go/src/github.com/elastic/filebeat/Godeps/_workspace/src/github.com/elastic/libbeat/service/service.go:31 +0x58

github.com/elastic/libbeat/service.ProcessWindowsControlEvents(0x1277c220)
        /go/src/github.com/elastic/filebeat/Godeps/_workspace/src/github.com/elastic/libbeat/service/service_windows.go:
59 +0x2cc
created by github.com/elastic/libbeat/service.HandleSignals
        /go/src/github.com/elastic/filebeat/Godeps/_workspace/src/github.com/elastic/libbeat/service/service.go:32 +0x1b
4
</pre>

**Comment by tsg** [comment]
Happens occasionally, not on every run.

**Comment by andrewkroh** [comment]
@tsg See this comment https://github.com/andrewkroh/eventbeat/blob/master/beat/eventbeat.go#L172. I think that is probably the cause. Running with `-d "service"` would help confirm this, if you can recreate the issue.

**Comment by tsg** [comment]
I can easily reproduce it. Here is the output:

<pre>
 C:\Users\vagrant\filebeat-1.0.0-rc1-windows> .\filebeat.exe -e -c .\filebeat.yml -d "service"
15/11/05 03:06:41.873661 geolite.go:52: WARN Couldn't load GeoIP database
15/11/05 03:06:41.877584 publish.go:245: INFO No shipper name configured, using hostname 'WIN-UMHB36DFNOC'
15/11/05 03:06:41.883422 service_windows.go:49: DBG  Windows is interactive: true
15/11/05 03:06:41.883422 crawler.go:77: INFO All prospectors initialised with 0 states to persist
15/11/05 03:06:42.921495 service.go:24: DBG  Received sigterm/sigint, stopping
15/11/05 03:06:42.922496 service.go:30: DBG  Received svc stop/shutdown request
nic: close of closed channel
</pre>

Does that confirm it?

**Comment by andrewkroh** [comment]
Yeah, that is the same issue -- two calls to `Beater.Stop()` from service.go. The channel needs to be protected from being closed more than once (or maybe use an [atomic_bool](https://github.com/andrewkroh/eventbeat/blob/master/beat/atomic_bool.go) instead of a channel).

**Comment by urso** [comment]
I'm not a huge fan of having a callback to directly handle signals (e.g. signal send multiple times, signal handler replaced or not after first call, some calls should not be run from within signal hander, ...). Does golang provide something similar to signalfd? Idea is to have main-thread block on signalfd (reading signals in event loop) and do proper shutdown.

**Comment by ruflin** [comment]
@urso Can this be closed with https://github.com/elastic/libbeat/pull/316
