### ISSUE TITLE
Create Solaris pkg for amd64

### ISSUE THREAD

**Issue by andrewkroh** [elastic/filebeat#206]
Filebeat can be cross-compiled for Solaris amd64 (not sparc) and it seems to work as expected. I would love to have a filebeat.pkg to install it and add it to service management facility (SMF) so that it can be managed with `svcadm`.

- [ ] Need to run our automated tests on Solaris. Does Elastic have a Solaris amd64 Jenkins slave?
- [ ] Update beats-packer to use fpm to create a package that installs files and sets up a servce

**Comment by gsaray101** [comment]
may I ask why there is not filebeat for solaris spark? Is there any other beats out there for solaris spark?

**Comment by schabluk** [comment]
+1 for Solaris spark package

**Comment by danievanzyl** [comment]
+1 sparc

**Comment by andrewkroh** [comment]
Glad to see their is interest. It should be possible to build for sparc, but it is not as easy as it is to build for amd64. Golang doesn't directly build for sparc (i.e. you cannot run `GOOS=solaris GOARCH=sparc go build`) but there is support for sparc if `gccgo` is used to compile. 

I have not tried using `gccgo` yet because I don't have a sparc machine to test the resulting binary on.

If anyone wants to contribute sparc support, I think the right place would be to enhance [beats-packer](https://github.com/elastic/beats-packer) with a container than has gccgo and do the build within that container.

**Comment by ruflin** [comment]
I suggest we keep try of this now in https://github.com/elastic/beats/issues/1464
