### ISSUE TITLE
Beats input: unhandled exception - FileBeat @timestamp field in wrong format

### ISSUE THREAD

**Issue by ricardojdsilva87** [elastic/filebeat#207]
Hello,

I found an issue when running the latest nightly build version of filebeat on a windows machine:

filebeat-nightly.latest-windows.zip
2015-11-04T21:31:11.000Z

The problem I've found is related to the @timestamp field, I don't know yet if the problem is from the beats plugin on logstash or from filebeat on the windows machine.

Currently I'm using this config, it's a test config, but it passes the filebeat testing flag:
filebeat:

-------------------------------------------------------------------------------------------

  prospectors:
    -
      paths:
        - C:\inetpub\logs\LogFiles\*\*.*
      type: log
      ignore_older: 100h
      fields:
        type: iis-logs
      #scan_frequency: 10s
output:
  logstash:
    enabled: true
    hosts: ["log.salesconquest.com:5000"]
    index: iis-logs
    tls:
      certificate_authorities: ['C:\Scripts\filebeat-1.0.0-beta4-windows\logstash-forwarder.crt']
      certificate: 'C:\Scripts\filebeat-1.0.0-beta4-windows\logstash-forwarder.crt'
      certificate_key: 'C:\Scripts\filebeat-1.0.0-beta4-windows\logstash-forwarder.key'

-------------------------------------------------------------------------------------------

On the logstash side I have:

input {
beats{
    port => 5000
   ssl => true
    ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
    ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
  }
}

The input config seems to be correct, the certificate works, this is the message that is generated on the cmd line after running the command:
filebeat.exe -c filebeat.yml -e -d "*"

2015/11/05 17:36:27.578052 publish.go:98: DBG  Publish: {
  "@timestamp": "2015-11-05T17:36:25.587Z",
  "count": 1,
  "fields": {
    "type": "iis-logs"
  },
  "fileinfo": {},
  "input_type": "",
  "line": 11,
  "message": "2015-11-05 10:56:57 10.1.1.87 POST /Service.svc - 50000 - 1
0.1.1.71 PHP-SOAP/5.3.3 - 200 0 0 17124",
  "offset": 786,
  "shipper": "pmi-core-promo-web-preprod",
  "source": "C:\\inetpub\\logs\\LogFiles\\W3SVC2\\u_ex151105.log",
  "type": "log"
}

I have after the filter and template for IIS logs (tested with sample files via manual input)

The error got on the logstash 2.0.0 instance:
![image](https://cloud.githubusercontent.com/assets/12953702/10977053/b5672f44-83e6-11e5-955d-a190eb073f3a.png)

It appears that the @timestamp field comes from filebeat in a wrong format, and the input field cannot process it.

It couldn't found any issue related on the logstash or filebeat repositories.
Is there any way of "formating" the timestamp on the filebeat side?
From my understanding logstash includes should include also the @timestamp field even if it is the receiving date (on my filter after the timestamp is switched by the time in the log message)

Thanks for the help

**Comment by tsg** [comment]
Hi @ricardojdsilva87 , I think you need to update the beats plugin in logstash:

    ./bin/plugin update logstash-input-beats

Please reopen if that doesn't solve the issue.

**Comment by urso** [comment]
yes, it's a known bug in beats input plugin <=0.9.2 . just update as Tudor described and you are good to go.

**Comment by ricardojdsilva87** [comment]
Hello,

It's working now together with filebeat filebeat-1.0.0-rc1 sending logs from a windows server.
I've upgraded recently to Logstash 2.0.0 and thought that the beats plugin was already on the latest version.
My bad...

Thanks for the help

**Comment by tsg** [comment]
Thanks for looping back, @ricardojdsilva87. It's always good to receive tickets so we know what issues people are hitting, so don't worry about it :-)
