### ISSUE TITLE
missing host field.

### ISSUE THREAD

**Issue by nxhack** [elastic/filebeat#208]
I tried firebeat 1.0.0-rc1, "host field" was  gone. LSF had host field. 
"shipper field" available. but I want Compatibility for LSF.

workaround: (filebeat.yml)
 .......
      fields:
        host: myhost
      fields_under_root: true
......

**Comment by monicasarbu** [comment]
We will add a section about the host in the LSF to Filebeat migration guide.  Thank you for reporting!

**Comment by tkuther** [comment]
Ditto for "file" field from LSF, which now seems to be "source".

**Comment by nxhack** [comment]
in LSF to Filebeat migration,  "offset field" mapping type is "long" in Filebeat, undefined in LSF. (I think declaration of mapping types is require.)

**Comment by mmuszkow** [comment]
Are there plans to have LSF-compatibility in case of _host_ field? It was really useful for me to have it automatically filled-in with FQDN in LSF (I don't know if it was done on LSF or on lumberjack side). I could have the same cfg file for every host and the LS input was consistend with _tcp_ and _udp_ plugins which also use _host_ field.

**Comment by nxhack** [comment]
LSF : logstash-forwarder (0.4.0) ->  LS (1.5.x) logstash-input-umberjack
                                                         LS (2.0.0) logstash-input-beats (0.9.6)
                                                                  + target_field_for_codec => "line"

Beats: filebeat (1.0.0-rc1)      ->      LS (2.0.0) logstash-input-beats (0.9.6)


    LSF     ->    Beats
-----------------------------
 host field -> shipper field
 file field   -> source field
-----------------------------

Missing "host field",  huge impact on LS filter configs.

**Comment by ruflin** [comment]
@nxhack Does the long offset field cause an issue for you?
By missing host field you mean that it has a different name and you would have to reconfigure your LS configs? Or do you mean it also has a different value?

**Comment by tsg** [comment]
@nxhack @mmuszkow @tkuther How about doing the field renaming in Logstash? I think it's as easy as dropping this at the top of your filters:

<pre>
filter {
    mutate {
        rename => {
            "shipper" => "host"
            "source" => "file"
        }
    }
}
</pre>

Would this work for your cases? Just trying to understand if it's worth it for us to introduce a compatibility flag or other messy things like that which we'll cost us in terms of maintenance.

**Comment by tsg** [comment]
Btw, another option is to use `add_field` instead of `rename` so you get both at the same time for migration purposes:

<pre>
filter {
    mutate {
        add_field => {
            "host" => "%{shipper}"
            "file" => "%{source}"
        }
    }
}</pre>

**Comment by nxhack** [comment]
@ruflin "offset field" is not issue. just information for the migration.
@tsg about host field issue, workaround is easy. but as LSF user, need compatibility.

**Comment by mmuszkow** [comment]
@tsg Actually, FB `shipper` field is not equal to LSF `host` field. `host` field always contains FQDN or IP address, `shipper` (by default) contains hostname. Also, it seems that `host` field is added on _lumberjack_ side, not by LSF and therefore this field can't be tampered with.

**Comment by tsg** [comment]
@mmuszkow hmm, it's weird because both LSF and FB use `os.Hostname()`. [Here](https://github.com/elastic/logstash-forwarder/blob/master/publisher1.go#L29) is the code for LSF, and [here](https://github.com/elastic/libbeat/blob/master/publisher/publish.go#L240) is the same for Filebeat (hope that I'm not reading one of them wrong). Looking at what `os.Hostname()` does, on Linux [it just reads](https://golang.org/src/os/sys_linux.go) from `/proc/sys/kernel/hostname`.

When you say it's added on the lumberjack side, you mean in `logstash-input-lumberjack`?

**Comment by mmuszkow** [comment]
@tsg Ok, you are right. `shipper` is hostname by default (I was fooled with different Linux/Windows behavior, on my Linux dist hostname = FQDN, on Windows it doesn't contain the domain name). Then, for me, the field name is not an issue anymore.

**Comment by tsg** [comment]
FYI, we are planning to clean up a bit the `shipper` thing, please see: https://github.com/elastic/libbeat/issues/281

**Comment by nxhack** [comment]
Take a look https://discuss.elastic.co/search?q=%22%25{host}%22

logstash-input-tcp, logstash-input-udp, logstash-input-lumberjack Typical usage.

**Comment by mmuszkow** [comment]
List of input plugins using _host_ field (grep didn't catch lumberjack):
```
[xxx@xxx /opt/logstash/vendor/bundle/jruby/1.9/gems]# grep -r 'event\["host"\]' *
logstash-input-exec-2.0.4/lib/logstash/inputs/exec.rb:        event["host"]    = @hostname
logstash-input-file-2.0.2/lib/logstash/inputs/file.rb:        event["host"] = @host if !event.include?("host")
logstash-input-generator-2.0.2/lib/logstash/inputs/generator.rb:          event["host"] = @host
logstash-input-generator-2.0.2/lib/logstash/inputs/generator.rb:        event["host"] = @host
logstash-input-generator-2.0.2/lib/logstash/inputs/generator.rb:        event["host"] = @host
logstash-input-http-2.0.2/lib/logstash/inputs/http.rb:          event["host"] = remote_host
logstash-input-irc-2.0.3/lib/logstash/inputs/irc.rb:          event["host"] = msg.user.host
logstash-input-log4j-2.0.4-java/lib/logstash/inputs/log4j.rb:        event["host"] = socket.peer
logstash-input-pipe-2.0.2/lib/logstash/inputs/pipe.rb:            event["host"] = hostname
logstash-input-stdin-2.0.2/lib/logstash/inputs/stdin.rb:          event["host"] = @host if !event.include?("host")
logstash-input-syslog-2.0.2/lib/logstash/inputs/syslog.rb:      event["host"] = host
logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:        event["host"] ||= client_address
logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:      event["host"] ||= client_address
logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:          event["host"] ||= client[3]
logstash-input-unix-2.0.4/lib/logstash/inputs/unix.rb:          event["host"] = hostname
logstash-input-zeromq-2.0.2/lib/logstash/inputs/zeromq.rb:          event["host"] ||= host
```

**Comment by urso** [comment]
host is not provided by input plugin. logstash-forwarder used to include a 'host' field: https://github.com/elastic/logstash-forwarder/blob/master/publisher1.go#L234

**Comment by nxhack** [comment]
Wow thx : https://github.com/logstash-plugins/logstash-input-beats/issues/25
