### ISSUE TITLE
Beta4 -> RC1, send fail

### ISSUE THREAD

**Issue by mmuszkow** [elastic/filebeat#209]
After updating filebeat from 1.0.0-beta4 to 1.0.0-rc1, my logs are no longer sent to LS. When I increase the logging level, I see:
```
DBG  Not harvesting, file didn't change: D:\maillogs\AgentLog20131209-1.LOG
INFO Error publishing events (retrying): EOF
INFO Error publishing events (retrying): EOF
INFO send fail
INFO backoff retry: 1s
INFO Error publishing events (retrying): EOF
INFO send fail
INFO backoff retry: 2s
INFO Error publishing events (retrying): EOF
INFO send fail
INFO backoff retry: 4s
DBG  Start next scan
DBG  scan path D:/maillogs/*.LOG
DBG  Check file for harvesting: D:\maillogs\AgentLog20131107-1.LOG
```
My filebeat config is:
```
filebeat:
  prospectors:
    -
      paths:
        - "D:/maillogs/*.LOG"
      input_type: log
      ignore_older: 87600h # just to debug, I have only 5 files in that dir
      document_type: agentlog
      scan_frequency: 10s

  registry_file: "D:/maillogs/registry"

output:
  logstash:
    enabled: true
    hosts: ["**cut**:5003"]
    tls:
      disabled: false
      certificate_authorities: ["D:/maillogs/logstash-forwarder.crt"]

logging:
  to_files: true
  level: debug
  files:
    path: "D:/maillogs"
    name: filebeat_log
```
logstash 2.0.0, logstash-input-beats 0.9.2, filebeat runs on Windows. With the beta4 version, everything worked fine. I added 2 new parameters to cfg in RC1: `input_type` and `document_type`.

**Comment by tsg** [comment]
> logstash-input-beats 0.9.2

Try to upgrade this, please:

     bin/plugin update logstash-input-beats

**Comment by urso** [comment]
please update to most recent plugin version as described by Tudor.

These fails are weird. what's netstat saying about TCP connections? Is filebeat still connected? How many connections does filebeat have open?

**Comment by mmuszkow** [comment]
Updating logstash-input-beats to 0.9.5 fixed the problem, thank you.
