### ISSUE TITLE
Compiling on FreeBSD

### ISSUE THREAD

**Issue by yonas** [elastic/filebeat#212]
I'm not sure how to compile filebeat on FreeBSD 10.2:

```
# bash
# go-freebsd-amd64 build -o freebsd-filebeat
main.go:4:2: cannot find package "github.com/elastic/filebeat/beat" in any of:
        /usr/local/go/src/github.com/elastic/filebeat/beat (from $GOROOT)
        /home/elasticsearch/filebeat-master/Godeps/_workspace/src/github.com/elastic/filebeat/beat (from $GOPATH)
        /home/elasticsearch/filebeat-master/src/github.com/elastic/filebeat/beat
godep: go exit status 1
```

What should I set `$GOPATH` to?

**Comment by ruflin** [comment]
@yonas As this is more golang specific then filebeat specific the best place to look at is probably the Golang docs here: https://golang.org/doc/code.html#GOPATH Let me know in case this doesn't work.

**Comment by yonas** [comment]
@ruflin It says to set it to the location of your workspace. What is the workspace location for filebeat?

**Comment by sbagmeijer** [comment]
Do you get it resolved  @yonas I have the same issue whatever path I try to set it keeps complaining.

**Comment by ruflin** [comment]
Can you just trying to run `make` inside the filebeat directory under github.com/elastic/filebeat ?

**Comment by sbagmeijer** [comment]
I get this then:

```
filebeat]# make
# first make sure we have godep
go get github.com/tools/godep
package bufio: unrecognized import path "bufio"
package bytes: unrecognized import path "bytes"
package encoding/json: unrecognized import path "encoding/json"
package errors: unrecognized import path "errors"
package flag: unrecognized import path "flag"
package fmt: unrecognized import path "fmt"
package io/ioutil: unrecognized import path "io/ioutil"
package os: unrecognized import path "os"
package path/filepath: unrecognized import path "path/filepath"
package io: unrecognized import path "io"
package strings: unrecognized import path "strings"
package encoding/xml: unrecognized import path "encoding/xml"
package log: unrecognized import path "log"
package net/http: unrecognized import path "net/http"
package net/url: unrecognized import path "net/url"
package os/exec: unrecognized import path "os/exec"
package regexp: unrecognized import path "regexp"
package strconv: unrecognized import path "strconv"
package go/ast: unrecognized import path "go/ast"
package go/parser: unrecognized import path "go/parser"
package go/printer: unrecognized import path "go/printer"
package go/token: unrecognized import path "go/token"
package path: unrecognized import path "path"
package runtime: unrecognized import path "runtime"
package sort: unrecognized import path "sort"
package text/template: unrecognized import path "text/template"
Makefile:10: recipe for target 'filebeat' failed
make: *** [filebeat] Error 1
```

**Comment by ruflin** [comment]
@sbagmeijer Hm, it seems like quite a few basic golang packages are missing. How did you install golang? What version of Golang are you using? I get the feeling that something went wrong during the setup of Golang. If GOPATH points for example to `/your/go/path/` Filebeat should be in `/your/go/path/src/github.com/elastic/filebeat`

**Comment by mdiehm** [comment]
Hi,

I got this working by installing (10.2-RELEASE )

go-1.5.1,1                     Go programming language
go-json-rest-1.0.0,1           Quick and easy way to setup a RESTful JSON API

Needed to go fast so I didn't fiddle with the paths but instead gave it what it was asking for a copy of beats-src under: /usr/local/go/src/github.com/elastic/beats/

goto: /usr/local/go/src/github.com/elastic/beats/filebeat/

make sure you change /bin/bash to what is appropriate on your system or link /bin/bash to your bash. Then "gmake" and  you're ready to filebeat.

**Comment by yonas** [comment]
Thanks @mdiehm  I'll try that.

**Comment by sbagmeijer** [comment]
@ruflin thank I did it with those directories like you said and it worked fine.

**Comment by ruflin** [comment]
@sbagmeijer :+1:

**Comment by ruflin** [comment]
@yonas Did you get it working? If yes, can you close the issue?

**Comment by yonas** [comment]
@ruflin  I'll try test this and let you know this week. Thanks for coming back to it.

**Comment by ari** [comment]
@yonas (or someone else)... would you be able to throw together a FreeBSD port for this app? Taking your build process and formalising it in a Makefile means that upgrading in the future should be much simpler for everyone.

**Comment by yonas** [comment]
@ari Definitely, I have some experience creating and maintaining FreeBSD ports.

**Comment by ari** [comment]
@yonas I've build a couple myself as well, so let me know if you need a hand.

**Comment by ruflin** [comment]
All follow up conversation should go into https://github.com/elastic/beats/issues/1034. Closing this issue.
