### ISSUE TITLE
On demand only

### ISSUE THREAD

**Issue by urso** [elastic/filebeat#219]
Start filebeat on demand only to forward a given set of files as is (registrar required?). Do not tail files to be send.
Stop filebeat once done.

Example use-case (replay without re-running any processing generating the events):
- Have logstash file output plugin write all events to file logging all events being indexed
- replay by sending written log files (with json) via filebeat to logstash

**Comment by ruflin** [comment]
An extended use case here could be, that every time files change, the full file is sent again. This can be interesting for more binary files. In this case a registrar would still be needed.

**Comment by ruflin** [comment]
Closing as duplicate of https://github.com/elastic/filebeat/issues/134
