### ISSUE TITLE
info logging should generate more useful information

### ISSUE THREAD

**Issue by nheath** [elastic/filebeat#228]
Ive been testing filebeat in windows in our test environments as a logstash-forwarder replacement, and am having significant problems with the reliability of event delivery into elasticsearch. I'll touch on those below, but they probably belong in a separate issue. I dont feel I have enough information to describe/understand the behavior yet--I have so far been unable to effectively troubleshoot the issues due to the logging captured. 

This issue is about a review and correction of various log levels. Even in test environments, *debug* generates waaaay too much data to leave on. I am logging *info* events. I think its important to generate logs that help one support the application, and filebeat is completely missing that. logstash-forwarder is much easier to see what it's doing, when the pipline gets blocked, and when it recovers. There are a number of bulleted points below, with examples.

* The lack of timestamps is tracked in a different issue elastic/libbeat#291. 
* INFO include harvester status (which files are being checked, skipped, and why), 
* INFO level for registrar successes (https://github.com/elastic/filebeat/blob/1.0.0-rc1/crawler/registrar.go#L99). This one alone would help greatly!
* WARN for the 'send fail' and retry messages below? 

I will be switching to debug log level in devel for a while to see if that helps, but unfortunately I wont be switching to filebeat in production yet :( 

My log file currently looks like this:

```
INFO Error publishing events (retrying): read tcp 10.34.161.86:52383->10.34.161.24:5044: wsarecv: An existing connection was forcibly closed by the remote host.
INFO send fail
INFO backoff retry: 1s
INFO Error publishing events (retrying): EOF
INFO send fail
INFO backoff retry: 2s
INFO Error publishing events (retrying): EOF
INFO send fail
INFO backoff retry: 1s
INFO Error publishing events (retrying): EOF
INFO send fail
INFO backoff retry: 1s
INFO Error publishing events (retrying): EOF
INFO send fail
INFO backoff retry: 2s
INFO Error publishing events (retrying): read tcp 10.34.161.86:52388->10.34.161.24:5044: wsarecv: An existing connection was forcibly closed by the remote host.
```

Compare this with logstash-forwarder's output

```
2015/11/11 23:59:24.633838 Stopping harvest of C:\Logs\AuctionSniper\SniperBidder\SniperBidder_20151110.log; last change was 24h0m6.3843332s ago
2015/11/11 23:59:25.238353 Registrar: processing 4 events
2015/11/11 23:59:25.239330 registry rotate: rename of .logstash-forwarder to .logstash-forwarder.old - rename .logstash-forwarder .logstash-forwarder.old: The process cannot access the file because it is being used by another process.
2015/11/11 23:59:25.239330 WARNING: (continuing) update of registry returned error: rename .logstash-forwarder .logstash-forwarder.old: The process cannot access the file because it is being used by another process.
2015/11/12 00:01:56.650417 Launching harvester on new file: C:\Logs\AuctionSniper\SniperBidder\SniperBidder_20151112.log
2015/11/12 00:01:56.651394 harvest: "C:\\Logs\\AuctionSniper\\SniperBidder\\SniperBidder_20151112.log" (offset snapshot:0)
2015/11/12 00:01:57.743232 Registrar: processing 4 events
2015/11/12 00:01:57.744209 registry rotate: rename of .logstash-forwarder to .logstash-forwarder.old - rename .logstash-forwarder .logstash-forwarder.old: The process cannot access the file because it is being used by another process.
2015/11/12 00:01:57.744209 WARNING: (continuing) update of registry returned error: rename .logstash-forwarder .logstash-forwarder.old: The process cannot access the file because it is being used by another process.
...
2015/11/12 13:24:41.888579 Registrar: processing 9 events
2015/11/12 13:24:41.890533 registry rotate: rename of .logstash-forwarder to .logstash-forwarder.old - rename .logstash-forwarder .logstash-forwarder.old: The process cannot access the file because it is being used by another process.
2015/11/12 13:24:41.890533 WARNING: (continuing) update of registry returned error: rename .logstash-forwarder .logstash-forwarder.old: The process cannot access the file because it is being used by another process.
2015/11/12 13:24:54.950604 Read error looking for ack: EOF
2015/11/12 13:24:54.950604 Setting trusted CA from file: gd_bundle-g2.crt
2015/11/12 13:24:54.953534 Connecting to [10.102.39.85]:6060 (sac-logstash.corp.auctiva.com) 
2015/11/12 13:25:09.954110 Failed to tls handshake with 10.102.39.85 WSARecv tcp 10.102.39.97:56188: i/o timeout
2015/11/12 13:25:10.954149 Connecting to [10.102.39.85]:6060 (sac-logstash.corp.auctiva.com) 
2015/11/12 13:25:25.955701 Failed to tls handshake with 10.102.39.85 WSARecv tcp 10.102.39.97:56189: i/o timeout
2015/11/12 13:25:26.955740 Connecting to [10.102.39.85]:6060 (sac-logstash.corp.auctiva.com) 
2015/11/12 13:25:28.098362 Connected to 10.102.39.85
2015/11/12 13:25:28.570059 Registrar: processing 16 events
```

Our elk stacks are small/simple (filebeat/logstash-forwarder --> logstash --> elasticsearch http) I estimate about 20% duplication of events--the events are identical, including the host/file/offset/message. This data comes from comparing one file over a given time range and comparing event count to lines in the file, with roughly 10k lines and 12k events in elasticsearch. I am also seeing one file from the same server that has zero events in elasticsearch; I am guessing filebeat decided not to harvest it ?

As mentioned, this issue is about adjusting logging levels to make this kind of troubleshooting easier. I provide details about my scenario only to give context. (but if you want to fix them all, I'm ok with that :))

**Comment by ruflin** [comment]
@nheath Thanks a lot for describing this issue in so much detail. We definitively need to clean up our logging on the libbeat and filebeat side to make it more useful for the user to easily understand what is going on. I think this issue is a very good starting to point to see what the expectations are. So you standard level of debugging you would like to have enabled is INFO, right?

About the missing events: We fixed a major bug here (https://github.com/elastic/libbeat/pull/296) but not sure if that is related to your issue. I assume you are sending data through logstash so you were also affected by this bug.

**Comment by nheath** [comment]
You're welcome. Thanks responding to issues so quickly!

I tend to adjust the logging level to the individual software, according to levels available, what data I want/need to see, and the volume it generates. I started with DEBUG and scale back until it generates what I'm looking for. That said, INFO tends to be a good happy medium.  I generally expect:

VERBOSE: (if it exists) all application status+data, e.g. all the recieved input/output events
DEBUG: all application status, used selectively/specificially for troubleshooting
INFO: useful information showing the app is functioning correctly, and high level behavior
WARN/ERROR: self explanitory

Regarding missing/duplicate events, thanks--i saw that issue as well, it felt like a harvesting issue not a delivery one, but i will need to re-test. I think the duplicate events were a logstash throughput problem, not with filebeat. I believe the events were being recieved by logstash, but could not be filtered and queued for output before the filebeat connection timed out waiting for acknowledgement.

**Comment by ruflin** [comment]
@nheath I started some "refactoring" of the log messages here: https://github.com/ruflin/filebeat/commit/72bb92823535a8f2e1d61a335d11ab32d7d47cad More work will also be needed in libbeat.

**Comment by ruflin** [comment]
More logging changes added here to libbeat: https://github.com/elastic/libbeat/pull/305

**Comment by ruflin** [comment]
Closing this issue as during the last month logging has been constantly improved. There is still potential for improvement but I think we reached now a reasonable state.
