### ISSUE TITLE
Support environment variables for propsector paths

### ISSUE THREAD

**Issue by alprema** [elastic/filebeat#230]
Hi,

It would be nice to support environment variables in the "paths" section of the config yaml to facilitate mass deployment.

It seems like it would involve an `ExpandEnv` around [there](https://github.com/elastic/filebeat/blob/aaddd57f10ca0431b4ebb9f935ca2c8da5d0ee57/crawler/prospector.go#L199) but I don't know the codebase enough (nor the language) to make a PR.

**Comment by ruflin** [comment]
@alprema Have a look at the conversation here for the environment variables: https://discuss.elastic.co/t/capture-environment-variable/33635

**Comment by alprema** [comment]
The discussion mentions possible side effects but I'm not sure to see what they could be, and the workaround of using a script is not very practical when using Filebeat as a Windows service.

Would it be a solution to have another setting like `expanded_path` that expands the variables or a setting in the yml (defaulting to false) that turns on expansion?

**Comment by ruflin** [comment]
@alprema The beats have a daemon which automatically restarts the beats in case it crashes. So having environment variables could be that a beat starts with different environment variables after a restart. This could on the one side be intended, on the other hand be unexpected.

Having a config option could be an option.

**Comment by alprema** [comment]
Ok so I guess the option is the solution, is there a development scheduled? (Unfortunately this becomes a bit too involved for someone like me that doesn't speak Go :/ ).

**Comment by ruflin** [comment]
@alprema We are currently working on GA and will discuss afterwards again what feature we will be able to take into the release. As soon as it is planned for a release, we will add labels.

**Comment by kri5** [comment]
No news on this feature?

It seems pretty important since it induces a breaking change compared to logstash-forwarder, as it supported environment variables.

It would make user migration to filebeat a lot easier.

**Comment by ruflin** [comment]
@kri5 This should answer your question: https://github.com/elastic/beats/pull/715 Closing this issue here. For further discussion please use discuss or the beats repo.
