### ISSUE TITLE
IIS Log Rotation seems to confuse FileBeat

### ISSUE THREAD

**Issue by Cylindric** [elastic/filebeat#236]
For a few days now I've come in to find that my webservers have zero logs in the Kibana dashboard. If I restart the FileBeat service on each server, the logs start to come in (starting with when they stopped, so nothing seems to be lost)

All I can think of is that it's something to do with the way that IIS rotates the log files out. I will set the logging to 'debug' in time for tonight's rotation, to see if anything shows up.

**Comment by ruflin** [comment]
@Cylindric Which version of filebeat are you using? Which Windows version? Let me know when you have some more data. I'm happy to assist here to get this fixed.

**Comment by Cylindric** [comment]
Oops, sorry, I missed the obvious!

Filebeat v1.0.0-rc1
Windows Server 2012R2.

I'll put the nightly on half the servers and RC1 on the rest, and see if it's been fixed already.

**Comment by ruflin** [comment]
Ok, thanks. Keep me posted.

**Comment by urso** [comment]
@ruflin @Cylindric would it make sense to test with most recent nightlies?

**Comment by Cylindric** [comment]
I have three servers running the nightly available as of yesterday, and three with RC1. I should have logs to look at today.

**Comment by Cylindric** [comment]
Typically, the problem has not re-appeared on any of the six servers I'm watching. I'll keep the logs running and report back if it happens again.

**Comment by ruflin** [comment]
@Cylindric Thanks

**Comment by Cylindric** [comment]
Apologies for letting this sit. I suspect it may have been caused by the same issue as this: https://github.com/elastic/beats/issues/905

**Comment by ruflin** [comment]
@Cylindric Should we close this an track it in elastic/beats#905?

**Comment by Cylindric** [comment]
Yes, that sounds fine.
