### ISSUE TITLE
Can't start Nightly Build filebeat-nightly.151115210455-windows due to "no host configuration"

### ISSUE THREAD

**Issue by Cylindric** [elastic/filebeat#237]
I'm just trying to get a recent build to work to test an issue, but either something has just changed in the config, or something is broken.

When I start FileBeat, I get the following error:

    2015/11/16 10:03:07.415072 geolite.go:52: WARN Couldn't load GeoIP database
    2015/11/16 10:03:07.470216 outputs.go:105: ERR failed to initialize elasticsearch plugin as output: no host configuration found
    2015/11/16 10:03:07.470216 beat.go:97: CRIT no host configuration found

My config file has ES output disabled (I'm using Logstash) so I don't think this should happen.

	filebeat:
	  prospectors:
		-
		  type: log
		  document_type: iis
		  paths:
			- "C:/inetpub/logs/LogFiles/*/*.log"
		
	  registry_file: "C:/ProgramData/filebeat/registry"

	output:
	  elasticsearch:
		enabled: false

	  logstash:
		enabled: true
		hosts: ["logstash:5044"]

	shipper:

FileBeat: filebeat-nightly.151115210455-windows
Windows Server 2012R2

**Comment by ruflin** [comment]
Yes, the "enabled" was removed. So now that a output is uncommented, it is enabled. Either remove the elasticsearch part or comment it out.

**Comment by Cylindric** [comment]
Aah, perfect thanks. I tried to look through the commits but didn't see anything obvious to my untrained  eye.

**Comment by ruflin** [comment]
@Cylindric Very hard to spot as this change is actually in libbeat and not filebeat.

**Comment by andrewkroh** [comment]
@Cylindric Thanks for testing from the nightly build. A good place to watch for breaking changes or an overall gist of what changed is the [CHANGELOG](https://github.com/elastic/libbeat/blob/master/CHANGELOG.md) in each of the project repos including libbeat.
