### ISSUE TITLE
Error message in logs when ignore_old reached

### ISSUE THREAD

**Issue by ogauchard** [elastic/filebeat#238]
I have the following messages in filebeat log file each time the ignore_old parameter is reached :

`2015-11-16T14:18:46+01:00 DBG  Stopping harvesting of file as older then ignore_old: %!(EXTRA string=d:/temp/application.log, string=Last change was: , time.Duration=5m5.0136652s)`

`2015-11-16T14:18:46+01:00 ERR File reading error. Stopping harvester. Error: EOF`

I am using the nightly build 2015-11-15T21:10:08.000Z on a Windows Server 2008 R2 platform.

**Comment by ruflin** [comment]
@ogauchard This is expected, but the printed out error is not great, especially the second one. Instead of printing the EOF for the second one, we should add the first message. Did it lead to any error on your side?

**Comment by ogauchard** [comment]
No error on my side.
I was just suprised to see this error message in logs (the second one) because as you said it is an expected behaviour and not an error.

**Comment by ruflin** [comment]
I'm trying to improve it here by sending the first error message and showing it in the second one. Like this EOF will not appear: https://github.com/ruflin/filebeat/commit/e115b279bd2cd7d86d0417f9cd32aa5fc47f0b5d#diff-c1434f19d1ba7920b4f4a6aa9c5e66b9R247

**Comment by ogauchard** [comment]
Does it really need to be an error message ? Maybe info or warning is more appropriate as it is an expected behaviour.

**Comment by ruflin** [comment]
With the introduction of close_older this error message will disappear. Closing. https://github.com/elastic/beats/pull/718
