### ISSUE TITLE
MIPS support

### ISSUE THREAD

**Issue by urso** [elastic/filebeat#240]
Follow up elastic/logstash-forwarder#539 about adding MIPS support to filebeat/beats.

Beats require go 1.5.x at the moment (due to some new symbols in standard library used by libbeat). With most recent gccgo being mostly compatible to go 1.4.2 we can try to remove strict 1.5.x dependency and try with gccgo again.

But it seems mips support will be added to go1.6 (https://github.com/golang/go/blob/master/doc/go1.6.txt#L13). Maybe waiting some more time will fix it for us.

**Comment by ruflin** [comment]
Closing as this is a general beat issue and less filebeat specific.
