### ISSUE TITLE
Growing Registrar File

### ISSUE THREAD

**Issue by ruflin** [elastic/filebeat#269]
The registrar writes the state of every file to disk. This happens for each file in the following format:

````
  "data.log.1": {
    "source": "data.log.1",
    "offset": 73366,
    "FileStateOS": {
      "inode": 8691996,
      "device": 16777220
    }
  },
```

Filebeat closes files after ignore_older to close the file handler but keeps the files in the registrar file as they could appear later again. Is this the case, filebeat can continue at the previous location.

Most of the time this is not an issue because the number of files during log rotation stays almost the same. This becomes an issue in case files are generated with random names. This means the registrar file is growing larger and larger over time.

Based on this I would propose the following solution:

Introduce a config variable `remove_state_older_then` where a timestamp can be defined after which the state should be removed from the config file. A better naming should be found here.

This would mean, the registrar file format needs to be extended:
````
  "data.log.1": {
    "source": "data.log.1",
    "offset": 73366,
    "lastread": timestamp
    "FileStateOS": {
      "inode": 8691996,
      "device": 16777220
    }
  },
```
The timestamp when the file was last seen must be added to know when it can be removed from the registrar.

See also discussion in https://github.com/elastic/filebeat/issues/181

**Comment by vinod8427** [comment]
I am good with this option but I have concern regarding that. Say for example I set "remove_state_older_then" to 10 min and the file in question lets say is ABC.log file. So as per the config settings, would you just remove ABC.log from registry file after 10 min? I am assuming you would rather check the existence of file before you take an action against it accordingly. In which case if ABC.log file is not updated for more than 10 min but file as such still exists then "remove_state_older_then" setting has no effect to it where as if ABC.log file is not present then the registry would be updated to remove the file name accordingly. Is my understanding correct?

**Comment by ruflin** [comment]
Closing in favor of: https://github.com/elastic/beats/issues/1022
