### ISSUE TITLE
Problem after upgrading logstash-input-beats

### ISSUE THREAD

**Issue by tnum5** [elastic/filebeat#277]
I am running filebeat 1.0.0-rc2 and I was getting the same symptoms as the described in this issue:

https://github.com/elastic/filebeat/issues/209

so I upgraded my beat plugin as suggested, now at 0.9.6. Now I get the same error at filebeat, however I get this in the logstash.log (which I was not getting before)

{:timestamp=>"2015-11-21T12:51:46.594000+0200", :message=>"Lumberjack input: unhandled exception", :exception=>#<NoMethodError: undefined method `force_encoding' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/util/charset.rb:14:in `convert'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-plain-2.0.2/lib/logstash/codecs/plain.rb:35:in `decode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-2.0.4/lib/logstash/inputs/lumberjack.rb:82:in `run'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-2.0.4/lib/logstash/inputs/lumberjack.rb:111:in `invoke'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:372:in `data'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:351:in `read_socket'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:363:in `ack_if_needed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:347:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:246:in `json_data_payload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:163:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:296:in `compressed_payload'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:163:in `feed'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:332:in `read_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/server.rb:315:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-2.0.4/lib/logstash/inputs/lumberjack.rb:110:in `invoke'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/concurrent-ruby-0.9.1-java/lib/concurrent/executor/executor_service.rb:515:in `run'", "Concurrent$$JavaExecutorService$$Job_1733552081.gen:13:in `run'"], :level=>:error}

My logstash is version 2.0.0. Is there something I can do about that?

Here is my filebeat configuration:

###################################################################
filebeat:
  prospectors:
      paths:
        - ./example.log
      input_type: log
  spool_size: 1
output:
  logstash:
    # The Logstash hosts
    hosts: [{snip}:5000"]
    tls:
      certificate_authorities: ["ca.pem"]
      certificate: "./logstash-forwarder.crt"
      certificate_key: "./logstash-forwarder.key"
shipper:
logging:
  files:
    rotateeverybytes: 10485760 # = 10MB
###################################################################

**Comment by tnum5** [comment]
Ooops. Never mind. 

Issue is described and solved here:

https://discuss.elastic.co/t/issue-with-filebeat-logstash-beats-input-unhandled-exception/33934

Sorry.

**Comment by ruflin** [comment]
@tnum5 Glad you found the solution.
