### ISSUE TITLE
Don't export fields if it's not configured

### ISSUE THREAD

**Issue by monicasarbu** [elastic/filebeat#278]
I am running Filebeat from master with the default configuration file and in Kibana I see that fields is exported with an empty value.
![screen shot 2015-11-22 at 10 52 04 am](https://cloud.githubusercontent.com/assets/11757159/11323061/6b6115bc-9107-11e5-8607-8c06054304e6.png)

**Comment by ruflin** [comment]
This is currently expected as we only don't send fields when fields_under_root is set to true: https://github.com/elastic/filebeat/blob/master/input/file.go#L90 I agree we don't have to send it in case there are no fields set. Could removing it have any affect on existing queries? To make sure fields has the right structure, we should also add it to the template file: https://github.com/elastic/filebeat/blob/master/etc/filebeat.template.json

**Comment by ruflin** [comment]
@andrewkroh Is this is still the case with the most recent fields implementation (didn't test)?

**Comment by andrewkroh** [comment]
If `fields` is not used in your configuration then `fields` will not be present in the output JSON.

**Comment by ruflin** [comment]
@andrewkroh Thanks. Based on this closing this issue.
