### ISSUE TITLE
Document Windows Setup Getting Started Guide

### ISSUE THREAD

**Issue by ruflin** [elastic/filebeat#295]
Currently Windows is not mentioned / documented in the Getting started guide: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-getting-started.html

This should be improved.

**Comment by dedemorton** [comment]
@ruflin Do we want a separate topic like we provide for the other Beats? I'm assuming the steps are similar, correct?

**Comment by monicasarbu** [comment]
@ruflin For Packetbeat and Topbeat we have another page in the docs describing how to install briefly the Beat under Windows: https://www.elastic.co/guide/en/beats/topbeat/current/_installing_topbeat_on_windows.html

It's true that we missed to add one for Filebeat. Would be great if you can sketch the steps on Windows and @dedemorton can make it nicer.

**Comment by monicasarbu** [comment]
@ruflin It might be that the steps to install Filebeat on Windows are similar with Packetbeat and Topbeat I didn't move the "Install Beat on Windows" page to libbeat as I need a place to include "specific" things for each Beat.

**Comment by ruflin** [comment]
@monicasarbu I think the steps are identical to topbeat. The part that for me is a little bit confusing is that we have "Installing Topbeat" as part of Getting started and "installation for windows". Shouldn't it be part of the getting started page too?

**Comment by monicasarbu** [comment]
@ruflin yes, I agree. It's better to have a section under the Getting Started -> Installing xbeat about how to install it under Windows and maybe include the rest of the info under a note.

**Comment by dedemorton** [comment]
@monicasarbu @ruflin I agree. Right now, we are treating Windows as a second-class citizen. I like the idea of treating all platforms equally, but we also need to think about the problem of having a Getting Started document that is becoming rather long. What's nice about the Unix platforms is that the installation steps are very clean (especially when you run them from the command line). I can take a stab at integrating the Windows steps in the Filebeat GS to see how it works, and then someone who has Windows can verify the steps.

**Comment by monicasarbu** [comment]
@dedemorton Great plan, thanks!

**Comment by ruflin** [comment]
Based on the discussion [here](https://discuss.elastic.co/t/learning-to-use-topbeat/35902/6), we should also add on how to install the template. @andrewkroh provided a nice example I think we can use: https://github.com/andrewkroh/winlogbeat/blob/feature/docs/docs/getting-started.asciidoc#loading-the-index-template-in-elasticsearch

**Comment by dedemorton** [comment]
Submitted a few PRs to close this issue:

https://github.com/elastic/beats/pull/412
https://github.com/elastic/beats/pull/452
