### ISSUE TITLE
Allow wildcard exclusion of files

### ISSUE THREAD

**Issue by danieljamesscott** [elastic/filebeat#298]
i.e. I want to include all files in a directory (/var/log/apps/*), but exclude those that have been rotated and zipped (*.gz).

Something like:
```
  - paths
      "/var/log/apps/*"
    exclude: "*.gz"
```
Previously, I was using logstash as an 'agent' to send logs to the server, and it was simple to do this with the 'file' input plugin, but this is not currently possible with filebeat.

**Comment by marminthibaut** [comment]
+1

**Comment by monicasarbu** [comment]
This feature is implemented in the PR https://github.com/elastic/beats/pull/563 and it will be available in the next release.
