### ISSUE TITLE
New command-line parameters for silent update

### ISSUE THREAD

**Issue by Cylindric** [elastic/filebeat#303]
I'm using Puppet to deploy and manage my ELK nodes, and currently the only way I can see to install and update a plugin (in this case logstash-input-beats) is to always install, then always update.

    /bin/echo -e "Y\n" | /opt/logstash/bin/plugin install logstash-input-beats
    /bin/echo -e "Y\n" | /opt/logstash/bin/plugin update logstash-input-beats

Is there a way of silently installing a plugin? What would be useful would be a parameter similar to apt-get's "-y" to auto-answer "Yes" to the prompt.

**Comment by urso** [comment]
I normally use 'yes | /opt/logstash/bin/plugin update logstash-input-beats'. But logstash plugin handling is better discussed on [logstash repository](https://github.com/elastic/logstash)

**Comment by Cylindric** [comment]
Hah! Sorry, must've switched from one repo to another before posting the issue. 

Appologies!
