### ISSUE TITLE
Filebeat should start even when all input files are inaccessable.

### ISSUE THREAD

**Issue by C0RD** [elastic/filebeat#316]
Hello,

I would like to have a switch to keep filebeat running even if all input-files are inaccessable. 

Currently filebeat checks for those inputfiles and if it can't open them, it stops with "No paths given. What files do you want me to watch?". But I have files configured, but they are not there yet (or due to permissions not readable for filebeat.)

This is needed, as the logfiles i want to track aren't there when  deployment and start of filebeat happens. Filebeat should just start (maybe complain in it's Logfile) and wait for those Logfile become available.

Thank you,
         Cord

**Comment by ruflin** [comment]
@C0RD I agree that the behaviour should be as described above. I have to look into the issue, but I think as not files are found no prospectors are started and filebeat just stops. Probably the same happens when all files disappear and are closed.

**Comment by ruflin** [comment]
@C0RD I just realised you opened the issue in the filebeat repo. Would you mind to open a new one in the beats repo? https://github.com/elastic/beats We merge all beats into one repo.

**Comment by C0RD** [comment]
I'm aware of that and the bug was a pebkac. Thanks for your answer.
