### ISSUE TITLE
More than 90% cpu utilization

### ISSUE THREAD

**Issue by SKatiyar** [elastic/filebeat#318]
I am pushing logs to logstash using filebeat. When `scan_frequency` is `0s` the cpu utilization spikes to 99.9%

**Comment by urso** [comment]
Well, setting scan_frequency to very low values, basically makes the crawler restart scanning the disk every so often. The crawler will actively scan the disk for new files and check if files have been renamed. Setting this value to 0, makes the crawler rescan your disk like crazy without ever taking a break. Also see [scan_frequency documentaion](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_scan_frequency) us recommending not to set this value to 0.

From my point of view this behaviour is fully expected. Why is it you want to set the value to 0?

**Comment by SKatiyar** [comment]
I was trying to push logs as soon as possible. Setting `scan_frequency` to `1s` is giving utilization of `3-0.3%` which is fine, but find it weird to have sudden jump to `90-99%` when `scan_frequency` is set to `0s`.
