### ISSUE TITLE
filebeat.log is filled with "ERR File reading error. Stopping harvester. Error: Stop harvesting as file is older then ignore_older: /path/to/log/file.log; Last change was: 24h0m7.07609164s"

### ISSUE THREAD

**Issue by shiplu** [elastic/filebeat#319]
I am facing this error a lot. All my instances'  `filebeat.log` is filled with it. 

```
ERR File reading error. Stopping harvester. Error: Stop harvesting as file is older then ignore_older: /path/to/log/file.log; Last change was: 24h0m7.07609164s

```

I checked all the files, They always get appended. Almost 2-3 times every second. And their mtime never get changed. I just dont get why filebeat is showing this error. I never set _ignore_older_ in filebeat config. So it's using 24h by default. 

```bash
$ which filebeat
/usr/bin/filebeat

$ /usr/bin/filebeat --version
filebeat version 1.0.0 (amd64)
```
- Why is this happening?
- How to fix it?

**Comment by urso** [comment]
their mtime never gets changed? How come? You using network shares? What kind of systems are you using (windows/linux)?

**Comment by shiplu** [comment]
Logs are inside an aws ebs volume. 
I am using `Ubuntu 12.04.5 LTS`.

I actually checked the log file using inotify and found its not getting changed at all.

**Comment by urso** [comment]
inotify doesn't work with network shares. That's why filebeat actively polls the file.

**Comment by ruflin** [comment]
There were several fixes in the most recent filebeat version related to missing updates. Please check the most recent version. If the error still exists, open an issue in the beats repo: https://github.com/elastic/beats/
