### ISSUE TITLE
Filebeat doesn't seem to be doing anything (new to this software) #321 

### ISSUE THREAD

**Issue by PeterV1982** [elastic/filebeat#322]
Follow up
somhow i don't know why
my code missed something
instead off 
- c://programdata//elasticsearch//logs//

the actual code says

- c://programdata//elasticsearch//logs//*.log

so the responce i got was useless :(

**Comment by ruflin** [comment]
@PeterV1982 as mentioned in https://github.com/elastic/filebeat/issues/321 please move the discussion to https://discuss.elastic.co/c/beats/filebeat
