### ISSUE TITLE
output > elasticsearch > ping?

### ISSUE THREAD

**Issue by lookingcloudy** [elastic/filebeat#323]
Why would this tool try to ping the host?  I assume this is ICMP?  ICMP is blocked everywhere!  The log file indicates that the ping failed and seems to not startup the output stream as a result.  Ahhh!  

We have spent 8 hours trying to get a simple filebeats working today.  Between very poor documentation and bugginess, still no go.  This ping request is one of many issues so far.

**Comment by andrewkroh** [comment]
Your assumption is wrong, this tool does not use ICMP. It verifies connectivity to Elasticsearch by [making](https://github.com/elastic/beats/blob/6adba2e1429161d5176b2210af169748bcd4fe32/libbeat/outputs/elasticsearch/client.go#L368) a simple HTTP HEAD request and verifying that the response code is `< 300`.

If this check fails then you should validate that the host running Filebeat has connectivity to Elasticsearch. You could use curl (`curl -v -XHEAD http://elasticsearch:9200`) and check the status code in the output.

**Comment by ruflin** [comment]
Closing as this does not seem to be a bug. In case the issue still exists, please open a discuss topic on https://discuss.elastic.co/c/beats/filebeat
