### ISSUE TITLE
Systemd journal support

### ISSUE THREAD

**Issue by cFire** [elastic/filebeat#325]
Are there any plans to include support for reading systemd journal files directly? As far as I'm aware the only option currently available is to configure syslog to write a normal log file too and have filebeat read from there. It would be nice to be able to cut out syslog as the middle man.

**Comment by ruflin** [comment]
There are currently no plans for this. As I don't have any knowledge of the systemd journal service I can't tell you how hard it would be to add a harvester for it.

As we merged all repository into one, please open a feature request here if needed: https://github.com/elastic/beats

On a side note: I just had a quick look at journal and there seems to be a Storage option which writes the files to disk. Couldn't this be used?
