### ISSUE TITLE
loadbalancing

### ISSUE THREAD

**Issue by runningman84** [elastic/filebeat#326]
I have two logstash servers and a bunch of filebeat agents. They are configured to send logs to both logstash servers. My metrics suggests that only the first logstash server gets messages.
In order to balance the traffic I could just randomize the server list. But it would be great if filebeat itself would choose a random logstash server...

**Comment by urso** [comment]
for questions regarding configuration please use [discuss forum](https://discuss.elastic.co/c/beats). Filebeat connect to logstash either in load-balance mode (connects to all logstash instances) or fail-over mode (select on logstash by random). Connections are via TCP, that is filebeat will not reconnect unless an error has occurred. Optionally you can employ some DNS based load-balancer returning different IP addresses for same domain.
