### ISSUE TITLE
Field containing file name

### ISSUE THREAD

**Issue by tr31z** [elastic/filebeat#327]
I use filebeat to send apache logs with this syntax : 

    -
      paths:
        - "/var/log/httpd/*.log"
      document_type: apache
      input_type: log
It's working great but since I am using a wildcard, I'd like to add a custom field containing the name of the file from which the message was read.
Is there a way to achieve this via the "fields:" parameter ?

**Comment by ruflin** [comment]
The filename is sent with each event in the source field, so not additional fields are needed. Fields you can only set per prospector. For questions please use in the future the discuss forum as we want to keep the Github issues for bugs: https://discuss.elastic.co/c/beats
