### ISSUE TITLE
Multiple files/types --> multiple outputs

### ISSUE THREAD

**Issue by adrianlop** [elastic/filebeat#328]
Hi,
I need to send from a host with filebeat, to a logstash server:
  - syslog lines
  - json logs from an app
I have logstash server configured with these 2 inputs:
```
input {
  beats {
    port => 5044
    codec => multiline {
      pattern => "(^[a-zA-Z.]+(?:Error|Exception): .+)|(^\s+at .+)|(^\s+... \d+)|(^\s*Caused by:.+)"
      what => "previous"
    }
  }
}

input {
  beats {
    port => 5054
    codec => json
  }
}
```
But I cannot configure filebeat to send to a port or another depending on the message type or path of the files I'm reading.
Please, be aware that `json filter plugin` **is not the same** as `json input codec`. My json logs are already prepared to be logstash-friendly (this is, they have the mandatory logstash fields).

Can you help please?
Are you planning to support this?

**Comment by ruflin** [comment]
The best way to do this at the moment is running two instances of filebeat. With one filebeat instance this is currently not supported.

**Comment by urso** [comment]
what's wrong with using `json filter` and `multiline filter` in logstash? You can change the `document_type` per prospector in filebeat and use the `[type]` field in logstash for filtering.

Please have this kind of discussion on discuss.elastic.co

**Comment by adrianlop** [comment]
@ruflin thank you. are you planning to support this in a single instance?
@urso json filter plugin is not the same as json input codec. the `json filter` has a required option `source`, which will take a json `field` and explode it in more`fields`.
the problem is that my logs are already json (not only a field, but the whole line). In fact, they're logstash-formatted (with `@timestamp`, `@version`, etc -- I'm using this `logstash-logback encoder` in our java apps: https://github.com/logstash/logstash-logback-encoder#standard-fields), that's the reason of using the input codec and not in the filter. I hope with this explanation is more clear.

**Comment by urso** [comment]
In beats input plugin the json_codec is executed on the `message` field. Makes me wonder what's wrong with setting `source` to `message` in `json filter`.

**Comment by adrianlop** [comment]
@urso no, I think the `json input codec` doesn't work like that (https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json.html). According to the docs, it takes the whole line as a json and decodes it, not only the `message` field.
In fact, I'm using it like that and it works as expected, example (this is the log line my app writes in the logfile):
```
{"@timestamp":"2016-01-19T08:46:43.886+00:00","@version":1,"message":"Slf4jLogger started","logger_name":"akka.event.slf4j.Slf4jLogger","thread_name":"xxxxx.actor.default-dispatcher-3","level":"INFO","level_value":20000,"HOSTNAME":"7basdf64c404"}
```
that's the reason I cannot use json filter with mandatory option `source`, because the source would be the whole line itself.

any ideas? thanks in advance.

**Comment by urso** [comment]
the events are embedded into an json object (with additional meta data) when being send to logstash. This event contains a `message` field with the line read from your file. After parsing the json-object in logstash beats plugin, the `message` field is passed to the `json codec` creating the final event object to be passed to the filter chain. It is up to the input plugin to decide on how codecs are used.

In case no codec is configured, the raw line (from your input file) is stored in the message field and should be parseable by `json filter`.

**Comment by adrianlop** [comment]
@urso thank you! I'll try this tomorrow and will come back to post some feedback :)

**Comment by Akshaykapoor** [comment]
@urso how can i send 2 different files from the same machine to different 2 logstash instances (on 2 different machines). Can you suggest what is the best approach for this. If it's running multiple instances, could you list out the different variables to be changed when creating a copy of the init script (Using centOS) ?

**Comment by urso** [comment]
@Akshaykapoor please use https://discuss.elastic.co for support questions. 2 filebeat instance would be required in this case. Configuration options depend on filebeat release 1.x or 5.x .

**Comment by ruflin** [comment]
Closing this as there are no near term plans to implement this.
