### ISSUE TITLE
Filebeat 1.1.0 multiline pattern regex error

### ISSUE THREAD

**Issue by wesleymusgrove** [elastic/filebeat#332]
I'm attempting to use Filebeat's new multiline functionality for logs that begin with an ISO 8601 formatted date and span multiple lines.  New log events always start with the date and every line after that needs to be merged into the previous line.  This ISO 8601 regex isn't intended to be super strict, I'm just simply checking for a valid format.

So here's my filebeat.yml multiline config:

    multiline:
      pattern: ^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})-(\d{2}):(\d{2})
      negate: false
      match: after

When I run `/etc/init.d/filebeat start` I get the following error:

    ERR Stop Harvesting. Unexpected encoding line reader error: error parsing regexp: invalid escape sequence: `\d`

What sort of regex is allowed?

**Comment by urso** [comment]
we're in the middle of documenting regex support as it's not so obvious. Check out elastic/beats#928 .
character classes like '\d' are not supported, but you can replace them via `[0-9]` or `[[:digit:]]`

please put these kind of question on our forum [discuss.elastic.co](discuss.elastic.co), as more people might be able to answer.
