### ISSUE TITLE
start filebeat as a background process

### ISSUE THREAD

**Issue by gnhuy91** [elastic/filebeat#335]
I know we can do something like `filebeat -c filebeat.yml &`, but I'd love to have an official run option.

**Comment by vinuguna** [comment]
you can install filebeat as a service. 

for example: 

# curl https://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -
# echo "deb https://packages.elastic.co/beats/apt stable main" |  sudo tee -a /etc/apt/sources.list.d/beats.list
# sudo apt-get update && sudo apt-get install filebeat
# sudo update-rc.d filebeat defaults 95 10
# service filebeat start

**Comment by vinuguna** [comment]
you can install filebeat as a service: 

 - curl https://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -
 - echo "deb https://packages.elastic.co/beats/apt stable main" |  sudo tee -a /etc/apt/sources.list.d/beats.list
 - sudo apt-get update && sudo apt-get install filebeat
 - sudo update-rc.d filebeat defaults 95 10
 - service filebeat start

**Comment by Vinu2903** [comment]
you can install filebeat as a service:

For example:

curl https://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add -
echo "deb https://packages.elastic.co/beats/apt stable main" | sudo tee -a /etc/apt/sources.list.d/beats.list
sudo apt-get update && sudo apt-get install filebeat
sudo update-rc.d filebeat defaults 95 10
service filebeat start

**Comment by andrewkroh** [comment]
This repo is no longer used.

You already opened this issue in the new repo elastic/beats#984
