### ISSUE TITLE
Is reload suported?

### ISSUE THREAD

**Issue by danielmotaleite** [elastic/filebeat#336]
Hi

when trying to do a filebeat reload i get:

      # systemctl reload filebeat
      Failed to reload filebeat.service: Job type reload is not applicable for unit filebeat.service.

Is there any way of doing reload? if not, can it be added? or at least restart if it is safe that i will not lose file position, so the command do not fail

Thanks for the help

**Comment by andrewkroh** [comment]
This repository is deprecated. Filebeat bugs and enhancements are now tracked in [elastic/beats](https://github.com/elastic/beats). For future questions use [Discuss](https://discuss.elastic.co/c/beats/filebeat).

Filebeat does not currently support config reload. It is safe to restart the Filebeat. The file position will not be lost.
