### ISSUE TITLE
Allow finding host FQDN

### ISSUE THREAD

**Issue by pickypg** [elastic/filebeat#339]
Apparently Go does not provide the FQDN on all systems (particularly Linux, it seems) because it checks `/bin/hostname` rather than `/bin/hostname -f`.

Here's the Go test showing that they accept the shortname: https://golang.org/src/os/os_test.go#L1341

It would be great if we could fill in the actual FQDN rather than an unexpected subset, but it does mean providing an appropriate mechanism for _every_ supported system (or falling back to the subpar behavior that comes out of the box).

/cc @andrewkroh

**Comment by pickypg** [comment]
As a workaround, #715 will allow environment variables to fill this in, but it still requires something else in the environment to be used.

**Comment by pickypg** [comment]
Maybe I should make this over at the beats repo?

**Comment by andrewkroh** [comment]
Yeah, please open it in the beats repo.

**Comment by pickypg** [comment]
https://github.com/elastic/beats/issues/1070 Done.
