### ISSUE TITLE
Filebeat lost the last line of log file

### ISSUE THREAD

**Issue by wenwenyun** [elastic/filebeat#342]

**Comment by ruflin** [comment]
@wenwenyun Can you please provide here some more information? Which version are you using? Which OS? Are you using file rotation? How did it happen?

**Comment by wenwenyun** [comment]
[root@YWser-01 product_lost_order_alert]# cat order.log | grep 2016030623061155008618416
merno=00000000000126,ordertime=20160306230615,prdordno=2016030623061155008618416
[root@YWser-01 product_lost_order_alert]# cat /etc/filebeat/filebeat.yml
filebeat:
  prospectors:
    -
      paths:
        - "/root/bin/product_lost_order_alert/order.log"
      document_type: "netapp_lost_order"

output:
  logstash:
    hosts: ["172.23.20.124:5504"]

logging:
  files:
    rotateeverybytes: 10485760 # = 10MB

=============================
[pay_ro@netapp-m-a log]$ cat /etc/filebeat/filebeat.yml
filebeat:
  prospectors:
   # -
   #   paths:
   #     - "/home/pay/resin-pro-4.0.36/log/jvm*"
   #   document_type: "resin_jvm_log"
    -
      paths:
        - "/home/pay/tdshome/trc/sys/sys.*"
      document_type: "tds_sys_trc"
    -
      paths:
        - "/opt/MirrorHA/log/*.txt"
      document_type: "rose_log"
    -
      paths:
        - "/home/pay/resin-pro-4.0.36/log/access.*"
      document_type: "resin-access"
output:
  logstash:
    hosts: ["172.23.20.124:5504"]

shipper:
  tags: ["netapp-servers"]

logging:
  files:
    rotateeverybytes: 10485760 # = 10MB
	
	
========================
ELK server:
input {
  beats {
    port => 5504
#   type => "resin-access"
#   type => "tds_sys_trc"
#   type => "rose_log"
#   type => "resin_jvm_log"
    codec => multiline {
      pattern => "^\s"
      what => "previous"
    }
  }
}

[root@logserver LogBackup]# cat ../_grokparsefailure | grep 2016030623061155008618416
{"@timestamp":"2016-03-06T18:17:46.831Z","message":"merno=00000000000126,ordertime=20160306230615,prdordno=2016030623061155008618416","@version":"1","beat":{"hostname":"netapp-m-a","name":"netapp-m-a"},"count":1,"fields":null,"input_type":"log","offset":2272935,"source":"/home/pay/resin-pro-4.0.36/log/access.log","tags":["netapp-servers","geoip","_grokparsefailure"],"type":"resin-access","host":"netapp-m-a"}
=================
in fact the message is come from YWser-01, I'm not sure whether the fault come from filebeat or logstash or mistack configure.

**Comment by ruflin** [comment]
Thanks for providing the config files. I still think I need more information. What is exactly happening that you didn't expect? Can you please open a discuss topic here with all this information and linking to this issue? https://discuss.elastic.co/c/beats/filebeat

We want to reserve Github for confirmed bugs. I will close this issue so we can continue the discussion on your discuss topic. Feel free to link it here.

**Comment by linrongfu26** [comment]
i user filebeat 1.1.2 and have the same problem ,my log file has 6 line,but the stdout in concole only print 5 line

**Comment by ruflin** [comment]
@linrongfu26 Can you open a topic on https://discuss.elastic.co/c/beats/filebeat with more details on your issue? In case we find this is a bug, we can either reopen this issue or create a new one.
