### ISSUE TITLE
filebeat connection refused

### ISSUE THREAD

**Issue by cernicb** [elastic/filebeat#345]
We use filebeat -> logstash to transport logs to graylog. As soon as filebeat logs:

> Error publishing events (retrying): EOF

it is followed by:

> Connecting error publishing events (retrying): dial tcp y.y.y.y:5043: getsockopt: connection refused

and connection to logstash is lost, and status check on logstash returns "not running". Logstash logs something like:

> {:timestamp=>"2016-03-08T16:08:27.658000+0100", :message=>"Beats Input: Remote connection closed", :peer=>"x.x.x.x", :exception=>#<Lumberjack::Beats::Connection::ConnectionClosed: Lumberjack::Beats::Connection::ConnectionClosed wrapping: EOFError, End of file reached>, :level=>:warn}

x.x.x.x and y.y.y.y ping each other.

After that point, there are no incoming logs on graylog. Once we start logstash again, everything is ok until new EOF arises. 

We use logstash-2.2.2-1.noarch with beat plugin 2.1.4, running on CentOS release 6.6, and filebeat version 1.1.1 (amd64) on CentOS release 6.4 (Final).

Output configuration on filebeat is:
`  logstash:
    # The Logstash hosts
    hosts: ["y.y.y.y:5043"]`
with one worker and no tls.

Input configuration on logstash is:
`input {
  beats {
    port => 5043
  }
}`

Any help appreciated.

**Comment by ruflin** [comment]
Have a look at the issues related to "remote connection closed": https://github.com/logstash-plugins/logstash-input-beats/issues?utf8=%E2%9C%93&q=is%3Aissue++Remote+connection

For questions please use the discuss forum as we want to keep Github for confirmed bugs: https://discuss.elastic.co/c/beats/filebeat Happy to dig deeper there. Closing this issue as also the filebeat repository is now part of the beats repository.

**Comment by ruflin** [comment]
@cernicb I just realised you also posted it here: https://discuss.elastic.co/t/filebeat-connection-refused-eof/43914 Please don't double post.
