### ISSUE TITLE
Filebeat reading multiple files

### ISSUE THREAD

**Issue by tony2944** [elastic/filebeat#350]
HI
We are using Filebeat to collect the logs from various folders.Example.A service is calling A1,A2 and A3.

All the logs are written in their respective folders.Filbeat is pushing the logs to logstash.In the logstash we are receiving and concat in the same order how the A service is calling.

IN our Filebeat configuration we set backoff_factor to .000001s.Becasue of this the CPU is reaching around 40%.If we set backoff factor to 1s then we are not able to concat the logs correctly and some of the logs are missedout becasue of 1s

IN logstash we are using aggregation plugin.Is there any way i can avoid these problem without reduce the backoff value

**Comment by urso** [comment]
Duplicate one: https://discuss.elastic.co/t/filebeat-cpu-high/51152
Please keep discussion to forum for now. For logstash specific questions, please consult logstash forum.
