### ISSUE TITLE
Create List of logstash-forwarder / Issue for beta4

### ISSUE THREAD

**Issue by ruflin** [elastic/filebeat#44]
Create a list of issues and pull request which should go into beta4. Split it up between filebeat and libbeat.

**Comment by ruflin** [comment]
I curated the following list to look at. I actually some issue are already resolved and it should be commented on the issue.

Filebeat:
* https://github.com/elastic/logstash-forwarder/issues/524
* https://github.com/elastic/logstash-forwarder/issues/523
* https://github.com/elastic/logstash-forwarder/pull/487/files
* https://github.com/elastic/logstash-forwarder/issues/484
* https://github.com/elastic/logstash-forwarder/issues/464
* Cross compiling (already implemented) https://github.com/elastic/logstash-forwarder/pull/452
* https://github.com/elastic/logstash-forwarder/issues/433
* https://github.com/elastic/logstash-forwarder/issues/349

Libbeat:
* https://github.com/elastic/logstash-forwarder/issues/510
* https://github.com/elastic/logstash-forwarder/issues/509

**Comment by sandstrom** [comment]
Filebeat looks neat! We're using logstash-forwarder in production and it's worked really well.

I see that TLS is being relaxed, which is great (in our case it's a locked down internal network).

My only wish would be for filebeat to take an unix `/etc/filebeat.d/` directory. It'll make configuration much easier (and less coupled) when multiple files are being watched. It would allow each service to drop their related configuration in that directory.

**Comment by ruflin** [comment]
@sandstrom Filebeat as one base config file and with the command line option -configDir any directory can be defined to crawl more config files. Will this help?

**Comment by sandstrom** [comment]
@ruflin Yes, that would be great! As long as it's in the [base] config file too, but I see that's already planned (change log entry quoted below).

> Command line config option -config was renamed to configDir. Should also be introduced as config file param in case we want to keep it

***

*As an aside I noticed that logstash-forwarder does support something similar since a few months back. It didn't support it when we implemented it, so that's why I didn't know.*

**Comment by ruflin** [comment]
Closing as issues resolved or follow up issue created.
