### ISSUE TITLE
Discuss template file for filebeat

### ISSUE THREAD

**Issue by tsg** [elastic/filebeat#66]
All beats have a default ES mapping template file. I added a very basic one as part of #65, but we should consider using one more similar with what Logstash provides by default: https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json

One thing to note is that Filebeat/libbeat currently doesn't have the capability of filling the `.raw` fields so that part is lost if going directly to ES.

**Comment by ruflin** [comment]
@tsg I removed the 1.0.0-beta4 label as I think we can add this later and the current one works for the first release. Please readd the label in case you disagree.

**Comment by veryhumble** [comment]
I am running filebeat 1.0.0rc1 on about 10 servers, also rolling out topbeat. 

Because I used to run logstash-forwarder, everything was added to the logstash index first, which was fine, but a bit crowded. So I followed the getting started guide at [Getting Started](https://www.elastic.co/guide/en/beats/libbeat/1.0.0-rc1/getting-started.html#logstash-setup) and added the kibana dashboards and configured logstash accordingly. Now I have indexes for file and topbeat but I am missing those ´.raw´ fileds on all string based fields. This makes it really unusable in Kibana due to our naming of the servers, for example "alfa-bravo-charlie", which gets splitted in the Terms filter.

Is there a simple solution, like adding something to output of logstash or do I have to change the mappings?

**Comment by ruflin** [comment]
Unfortunately the current mapping of filebeat does not define a "mapping" for the hostname / name field. I think in general we should set it to not_analyzed which then would not required the .raw field. What are fields woud you required to be not analyzed?

As you said, logstash provides for its own indexes the raw field for all string: https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/2.0/lib/logstash/outputs/elasticsearch/elasticsearch-template.json#L18 It's a good point and we should discuss if we should do the same for the beats.

The easiest and long term solution is probably to create a new index with the required mapping and reindex as a mapping change on the existing index is not possible.

**Comment by ruflin** [comment]
@veryhumble Would it possible for you to list the fields from topbeat and filebeat which you would prefer not be indexed? This would be very helpful for the discussion if we should update our mapping with certain fields not be analysed or if we should have a "general" mapping type rule like logstash does. The nice part about beats is, that we exactly know which fields are going to be sent, so we should be able to say in advance, which mapping is needed.

**Comment by tsg** [comment]
@veryhumble, just to clarify, you are sending from Filebeat directly to Elasticsearch? In that case, if you load [our template](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-getting-started.html#filebeat-template) it should set all fields except `message` to be `not_analyzed`.  For Beats, in general, we know what each field means so we can avoid storing it twice (analyzed and .raw for not analyzed). Filebeat is a bit of an exception, because there you usually want to parse the message, but in that case you would use Logstash for parsing, which adds the `.raw` fields.

**Comment by veryhumble** [comment]
sorry for my late answer.

I route everything from filebeat and topbeat through logstash. Also, I could fix the issue by using those templates for file- and topbeat in their github repositories. Now I have some sort of memory problem on the logstash side, it dies after about 6 hours, but thats another issue.

Using the templates, I was able to use the shipper field in Kibana correctly. Fortunately I dont need historical data yet, so I can easily clean all indices, which I may have to do again upon updating to the, hopefully soon, available GA release.

**Comment by ruflin** [comment]
@veryhumble Good to hear you found a solution. Be aware that shipper was renamed to beat.name in RC2. In case you opened a LS issue, it would be nice to link it here in case it is related to beats or beats-input-plugin.

**Comment by ruflin** [comment]
Closing this as now all beats have a template by default.
