### ISSUE TITLE
Allow paths with wildcard directories

### ISSUE THREAD

**Issue by roji** [elastic/filebeat#68]
In some cases log files are grouped into subdirectories, and it seems impossible to specify the following for logstash-forwarder: /syslog/log/**/*.

This capability is supported by logstash, see this conversation.

(Issue copied from https://github.com/elastic/logstash-forwarder/issues/532)

**Comment by Steiniche** [comment]
I currently have this working, on windows, with: 
paths:
      - C:/logs/*/*.log

**Comment by fatmanmclone90** [comment]
Wildcards for directories not working for me either.  Would be a useful feature +1

**Comment by tony2944** [comment]
- for me /opt/logs/*/operational.log is working.

**Comment by ruflin** [comment]
Closing this in favor of https://github.com/elastic/beats/issues/2084
