### ISSUE TITLE
Non-string fields should be supported

### ISSUE THREAD

**Issue by magnusbaeck** [elastic/filebeat#69]
The `fields` parameter in the prospector configuration is of type `map[string]string` and therefore only supports string fields. Is there any good reason for this? The message serialization in beat/filebeat.go uses the MapStr type from github.com/elastic/libbeat/common which is defined as `map[string]interface{}` so it should be fine to pass e.g. array fields.

See also https://discuss.elastic.co/t/how-to-setup-tags/31454.

**Comment by ruflin** [comment]
I currently don't see a reason why we should not be able to change it as you mentioned above. In case we change it, we should add some tests to make sure it works as expected. Would you be able to open a pull request with these changes?

**Comment by magnusbaeck** [comment]
I can prepare a PR as soon as my new CLA is in place. I'm told it's just the paperwork left.

**Comment by ruflin** [comment]
@magnusbaeck Cool, looking forward to it.

**Comment by ruflin** [comment]
See also for discussions: https://github.com/elastic/logstash-forwarder/issues/65

**Comment by magnusbaeck** [comment]
This one's next on my list. I should be able to have a PR ready within a week.

Should we allow anything under `fields`? Top-level arrays must obviously be okay (that's the whole point of this issue), but is there any reason to disallow dictionaries and whatever nested structures people might come up with?

Taking a glance at the test cases it doesn't seem like you're very fond of the table-driven tests that the Go folks recommend. Should I follow suit?

**Comment by ruflin** [comment]
I don't see a reason to set limitations under fields and nested structure. It will be up to the people to figure out how they can still do queries based on the structures they created.

About the table-driven tests: Just had a look at it. Looks promising. Go for it.

**Comment by magnusbaeck** [comment]
This turned out to be slightly more complicate than expected. When HarvesterConfig.Fields is unmarshaled from YAML, nested dictionaries become map[interface{}]interface{} instead of map[string]interface{} and the former can't be marshalled to JSON. I'll probably have to change the formal type of HarvesterConfig.Fields to a custom type that implements [yaml.Unmarshaler](https://godoc.org/gopkg.in/yaml.v2#Unmarshaler).

**Comment by ruflin** [comment]
Ok. Probably best to use golang 1.5.2 for that as there seemed to be some issues with map[interface{}]interface{} in 1.5.1 https://github.com/golang/go/issues/12536
