### ISSUE TITLE
Improve filebeat shutdown process

### ISSUE THREAD

**Issue by ruflin** [elastic/filebeat#77]
Currently the shutdown process of filebeat is not fully predictable. The implementation should be improved with WaitGroups. For more details see: https://github.com/elastic/filebeat/pull/75/files#r41322074

**Comment by andrewkroh** [comment]
I had filebeat running for about ~4 hours on OSX and shut it down with Ctrl+C and it panicked with the attached [stacktrace](https://github.com/elastic/filebeat/files/16438/stacktrace.txt)

**Comment by tsg** [comment]
I get the same on OS X when running it for only a few seconds. But I set it to read `/var/log` so it's about killing it while busy.

**Comment by ruflin** [comment]
Shutdown process of filebeat was rewritten for 5.0.0. This issues should now not happen anymore. Closing.
