### ISSUE TITLE
Finish Lumberjack Implementation

### ISSUE THREAD

**Issue by ruflin** [elastic/filebeat#79]
See also:
* https://github.com/elastic/logstash-forwarder/issues/178
* https://github.com/logstash-plugins/logstash-input-lumberjack/issues/55

**Comment by ruflin** [comment]
This also relates to https://github.com/elastic/libbeat/issues/3

**Comment by urso** [comment]
we're basically waiting for logstash team. On beats side we are finished.

**Comment by urso** [comment]
we decided to create new input plugin for logstash to go forward. See https://github.com/logstash-plugins/logstash-input-beats for progress.

**Comment by tyrken** [comment]
Is this a new protocol or just a fork?

If a new protocol will you take on some of @driskell experience with issues in the old protocol when making https://github.com/driskell/log-courier?

**Comment by urso** [comment]
at the moment it's just a fork with some minor additions (will not solve all known issues): slow start (smaller batches), shrinking batch sizes on failure and partial ack.

lumberjack implementation in libbeat.
logstash plugin available: https://github.com/logstash-plugins/logstash-input-beats.
