### ISSUE TITLE
Check where the .filebeat registry file is created when installed from pacakges

### ISSUE THREAD

**Issue by tsg** [elastic/filebeat#82]
Posted so I don't forget about it. Writing the registry file in the CWD would not be ideal because that is set to the root folder by default. Somewhere in /var might be better.

**Comment by tsg** [comment]
On a Windows 2012 system, the file is created at `c:\Windows\SysWOW64\.filebeat`.

**Comment by tsg** [comment]
Yeah, it's `/.filebeat` on a Debian system.

I guess the Windows one is OK (don't really know what the best practices are), but the Linux one seems wrong to me, so we should discuss if we want to change it. Maybe `/var/data/filebeat` or something like that? I think but am not sure that the Logstash-Forwarder packages set it somewhere in `/opt`.

**Comment by ruflin** [comment]
@tsg `/.filebat` also seems quite wrong to me. Could we set it by default in the same directory as the executable is? This should also work on Windows.

**Comment by tsg** [comment]
That would be `/usr/bin`, not sure it's much better. I'm thinking to have the Linux part of the `install_cfg` target modify the configuration file to have `registryfile: /var/lib/filebeat/.filebeat`. In which case we'd also need to make sure Filebeat creates that folder if it doesn't exit.

**Comment by urso** [comment]
+1 for /var/lib/filebeat on unix system. But where to put on windows?

**Comment by tsg** [comment]
We put the logs under `c:\ProgramData\filebeat\Logs`, so something like `c:\ProgramData\filebeat\.filebeat` or `c:\ProgramData\filebeat\registry.json` sound good to me. Then again, people are less likely to mess with it if it's in the system folder.

**Comment by urso** [comment]
+1

do we protect the file from being used by multiple filebeat instances?

**Comment by tyrken** [comment]
+1 for C:\ProgramData\filebeat\registry.json on Windows - keep the system folder clear & dont write to C:\ProgramFiles outside installers.

Does it have to be ".filebeat" on Linux? It's not really a hidden file or per-user profile, more a db in the right place (/var/lib/filebeat).

**Comment by ruflin** [comment]
In case it is not a hidden file, I think it makes sense to add .json to make clear the content type. The main reason to make it hidden is that it is not "removed" accidentally, but in case it is hidden in the system folders, this is not need.

@tsg Should we make the default perhaps also platfrom specific?

**Comment by urso** [comment]
please do not store hidden files in /var/lib/whatever. If an admin removes this file it's his problem.

**Comment by tsg** [comment]
Agreed to make it non-hidden when it goes to `/var/lib` or `ProgramData`. But I'm thinking we should leave out the `.json` extension since this is after all an implementation detail of the registry and definitely don't want people to hand edit it.

**Comment by tsg** [comment]
Two tasks to do here:

* [ ] Fliebeat should be able to mkdir the path up to the configured registry file if it doesn't exit
* [ ] Make the `install-cfg` target customize the path depending on the platform

**Comment by ruflin** [comment]
@tsg Ok for me to leave out the .json. About the dir creation: This should probably be done by the installer and not filebeat itself?

**Comment by tsg** [comment]
Now done via the pull requests above.
