### ISSUE TITLE
Multiline grouping functionality at the shipper level

### ISSUE THREAD

**Issue by acchen97** [elastic/filebeat#89]
Multiline grouping is often better done closer to the data source, so Filebeat should effectively have this functionality.

**Comment by tsg** [comment]
Agreed and we plan to do this soon after releasing the GA.

**Comment by ruflin** [comment]
For more details / inputs see also: https://github.com/elastic/logstash-forwarder/issues/309

**Comment by jhmartin** [comment]
Pretty much any java application has to deal w/stack traces, so collapsing multi-line inputs into one record is critical.

**Comment by jordansissel** [comment]
@jhmartin your comment sounds like you're afraid that this feature won't be implemented? Has there been any indication of that? I'm a bit confused :)

**Comment by jhmartin** [comment]
@jordansissel No indication, I'm voicing support for it with the hopes it gets nudged up in the priority queue.

**Comment by passing** [comment]
@jhmartin will there be a configurable timeout to avoid that the last message in a logfile is not shipped until another message is added?
In logstash (file-input) this is not supported and a real problem for us, as important log messages can be delayed very long when there are infrequent writes to a logfile.

**Comment by ruflin** [comment]
@passing Mutiline is still in the planning phase. Having a timeout is something we already started to think about.

**Comment by varh1i** [comment]
@jordansissel "your comment sounds like you're afraid that this feature won't be implemented? Has there been any indication of that?"
Processing multilines with multiple workers is an issue for a long time already, Nov. 2014 as of https://github.com/elastic/logstash-forwarder/issues/309

Do you have a rough estimation for implementing this?

**Comment by tsg** [comment]
@varh1i the current target is around middle of Jan (essentially next Filebeat release after 1.0.0). Note that we're doing time based releases, which means that if the feature slips, it will slip with ~6 weeks.

**Comment by varh1i** [comment]
ok, thank you for the quick reply

**Comment by ruflin** [comment]
See https://github.com/elastic/filebeat/issues/301 for the technical implementation proposal.

**Comment by KIVagant** [comment]
+1 The really important feature. Subscribed.

**Comment by batmat** [comment]
+1. Currently using logstash to ship logs, I was willing to make my logs collection architecture a bit cleaner by having a voluntarily less processing capable tool on the shipping side, but indeed w/o multiline aggregation in the source I'm not sure my logs would ever get a chance to be aggregated correctly afterwards :-).

IIUC, this issue is actually fixed now that https://github.com/elastic/beats/pull/570 has been merged, right?

**Comment by andrewkroh** [comment]
Multiline support has been added (elastic/beats#461) and is being released in Filebeat 1.1.0 (tentatively early next week).

**Comment by KIVagant** [comment]
Thank you for information.

**Comment by batmat** [comment]
![](https://media.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif)
