### ISSUE TITLE
Support of round robin on down stream servers

### ISSUE THREAD

**Issue by astrobounce** [elastic/filebeat#98]
Hey ,

Currently logstash forwarder doesn't support load balancing of down stream servers , it just supports if one server is dead then only it connects to next server mentioned in the list . This will help in Scalability feature , one shipper will not be overloaded because of logs .

Regards
Arvind

**Comment by andrewkroh** [comment]
Hi @astrobounce, I am happy to inform you that load balancing is now a feature. It was implemented in libbeat so that the feature can be shared by all of the Beats.

See: https://www.elastic.co/guide/en/beats/libbeat/master/configuration.html#_loadbalance

**Comment by allenmchan** [comment]
@andrewkroh  should there be some mention that multiline (whether codec or filter) would not work if load balance is turned on?

**Comment by urso** [comment]
@allenmchan 1) this is indeed an issue. See #89 to track status of multiline support. 2) Due to internal architecture inherited from LSF, filebeat currently does not really profit from load balancing #106.
